/**
 * Priority Vendor Profiles for HTML Crawling
 *
 * Spekd is a trade-only platform. These are established home furnishings
 * manufacturers and trade brands that sell through retailers, designers,
 * reps, and dealer networks.
 *
 * NO consumer/DTC brands: no IKEA, Wayfair, West Elm, Pottery Barn,
 * CB2, Target, Amazon, Article, Castlery, or any mass-market retailer.
 */

export const priorityVendors = [
  {
    id: "bernhardt",
    name: "Bernhardt",
    domain: "bernhardt.com",
    profile: {
      asset_hosts: ["bernhardt.com", "bernhardt.scene7.com", "images.bernhardt.com"],
      title_suffixes: ["| Bernhardt", "| Bernhardt Furniture"],
      product_path_tokens: ["shop"],
      reject_path_tokens: ["search", "showrooms"],
      image_path_hints: ["/is/image/", "/products/", "/images/", "/media/"],
      listing_path_tokens: ["shop", "furniture", "seating"],
    },
    discovery: {
      search_paths: ["/shop/?ReferringState=Search&q={query}"],
      category_paths: {
        "swivel chair": ["/shop/?Sub-Category=Swivel%20Chairs&$MultiView=Yes&orderBy=OutdoorPosition,Id"],
        chair: ["/shop/?Sub-Category=Chairs&$MultiView=Yes&orderBy=LivingPosition,Id"],
        sofa: ["/shop/?Sub-Category=Sofas&$MultiView=Yes&orderBy=LivingPosition,Id"],
      },
    },
  },
  {
    id: "hooker",
    name: "Hooker Furniture",
    domain: "hookerfurnishings.com",
    flat_product_urls: true,
    profile: {
      asset_hosts: ["hookerfurnishings.com", "hookerfurniture.com", "images.hookerfurniture.com"],
      title_suffixes: ["| Hooker Furniture", "| Hooker Furnishings"],
      product_path_tokens: ["product", "products", "item"],
      reject_path_tokens: ["search", "catalogs", "collections", "inspiration", "customer", "cms"],
      image_path_hints: ["/products/", "/images/", "/media/", "/catalog/"],
      listing_path_tokens: ["products", "living-room", "seating", "accent-chairs"],
    },
    discovery: {
      search_paths: ["/catalogsearch/result/?q={query}"],
      category_paths: {
        chair: ["/accent-chairs"],
        "swivel chair": ["/accent-chairs"],
        sofa: ["/sofas-sectionals"],
      },
    },
  },
  {
    id: "century",
    name: "Century Furniture",
    domain: "centuryfurniture.com",
    profile: {
      asset_hosts: ["centuryfurniture.com", "cdn.centuryfurniture.com"],
      title_suffixes: ["| Century Furniture"],
      product_path_tokens: ["product-detail", "product", "products", "item"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/prod-images/", "/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/catalogsearch/result/?q={query}"],
      category_urls: [
        "/products.aspx?TypeID=81",
        "/products.aspx?TypeID=32",
        "/products.aspx?TypeID=72",
        "/products.aspx?TypeID=34",
        "/products.aspx?TypeID=134",
        "/products.aspx?TypeID=132",
        "/products.aspx?TypeID=84",
        "/products.aspx?TypeID=83",
        "/products.aspx?TypeID=76",
        "/products.aspx?Search=recliner",
        "/products.aspx?search=sectional",
        "/products.aspx?TypeID=48",
        "/products.aspx?TypeID=55",
        "/products.aspx?TypeID=79",
        "/products.aspx?TypeID=82",
        "/products.aspx?TypeID=70",
        "/products.aspx?TypeID=61",
        "/products.aspx?TypeID=73",
        "/products.aspx?TypeID=74",
        "/products.aspx?TypeID=25",
        "/products.aspx?TypeID=29",
        "/products.aspx?SubTypeID=82",
        "/products.aspx?TypeID=143",
        "/products.aspx?TypeID=137",
        "/products.aspx?TypeID=139",
        "/products.aspx?TypeID=140",
        "/products.aspx?TypeID=148",
        "/products.aspx?TypeID=142",
        "/products.aspx?TypeID=141",
        "/products.aspx?TypeID=146",
        "/products.aspx?TypeID=138",
        "/products.aspx?TypeID=136",
      ],
    },
  },
  {
    id: "vanguard",
    name: "Vanguard Furniture",
    domain: "vanguardfurniture.com",
    profile: {
      asset_hosts: ["vanguardfurniture.com", "cdn.vanguardfurniture.com"],
      title_suffixes: ["| Vanguard Furniture"],
      product_path_tokens: ["product", "products", "item"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/search?q={query}"],
    },
  },
  {
    id: "lexington",
    name: "Lexington Home Brands",
    domain: "lexington.com",
    flat_product_urls: true,
    profile: {
      asset_hosts: ["lexington.com", "cdn.lexington.com"],
      title_suffixes: ["| Lexington Home Brands", "| Lexington"],
      product_path_tokens: ["product", "products", "item"],
      reject_path_tokens: ["search", "collections", "customer", "cms", "catalogsearch"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/catalogsearch/result/?q={query}"],
    },
  },
  {
    id: "universal",
    name: "Universal Furniture",
    domain: "universalfurniture.com",
    profile: {
      asset_hosts: ["universalfurniture.com", "cdn.universalfurniture.com"],
      title_suffixes: ["| Universal Furniture"],
      product_path_tokens: ["product", "products", "item"],
      reject_path_tokens: ["search", "collections", "blog"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/search?q={query}"],
    },
  },
  {
    id: "hickory-chair",
    name: "Hickory Chair",
    domain: "hickorychair.com",
    profile: {
      asset_hosts: ["hickorychair.com", "cdn.hickorychair.com"],
      title_suffixes: ["| Hickory Chair"],
      product_path_tokens: ["product", "products", "item"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/search?q={query}"],
    },
  },
  {
    id: "theodore-alexander",
    name: "Theodore Alexander",
    domain: "theodorealexander.com",
    profile: {
      asset_hosts: ["theodorealexander.com", "cdn.theodorealexander.com"],
      title_suffixes: ["| Theodore Alexander"],
      product_path_tokens: ["product", "products", "item"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/catalogsearch/result/?q={query}"],
    },
  },
  // Four Hands — REMOVED (blocklisted, see vendor-blocklist.mjs)
  {
    id: "caracole",
    name: "Caracole",
    domain: "caracole.com",
    profile: {
      asset_hosts: ["caracole.com", "cdn.caracole.com"],
      title_suffixes: ["| Caracole"],
      product_path_tokens: ["product", "products", "item"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/catalogsearch/result/?q={query}"],
    },
  },
  {
    id: "baker",
    name: "Baker Furniture",
    domain: "bakerfurniture.com",
    profile: {
      asset_hosts: ["bakerfurniture.com", "cdn.bakerfurniture.com", "baker-prod.imgix.net"],
      title_suffixes: ["| Baker Furniture", "| Baker"],
      product_path_tokens: ["living", "dining", "bedroom", "outdoor", "workspace"],
      reject_path_tokens: ["search", "collections", "design-story"],
      image_path_hints: ["/products/", "/images/", "/media/", "imgix.net"],
      min_path_segments: 4,
    },
    discovery: {
      search_paths: ["/catalogsearch/result/?q={query}"],
      category_urls: [
        "/living/seating/sofas/",
        "/living/seating/chairs/",
        "/living/seating/sectionals/",
        "/living/seating/chaises/",
        "/living/seating/benches/",
        "/living/seating/ottomans/",
        "/living/storage-display/chests/",
        "/living/storage-display/cabinets/",
        "/living/storage-display/servers/",
        "/living/storage-display/etageres/",
        "/living/tables/tables/",
        "/living/lighting/",
        "/living/accessories/accessories/",
        "/dining/tables/tables/",
        "/dining/seating/chairs/",
        "/dining/seating/barcounterstools/",
        "/dining/seating/benches/",
        "/bedroom/beds/beds/",
        "/bedroom/tables/nightstands/",
        "/bedroom/tables/tables/",
        "/workspace/desks/",
        "/outdoor/seating/benches/",
        "/outdoor/seating/chairs/",
        "/outdoor/seating/chaises/",
        "/outdoor/seating/ottomans/",
        "/outdoor/seating/sectionals/",
        "/outdoor/seating/sofas/",
        "/outdoor/seating/stools/",
        "/outdoor/tables/tables/",
        "/outdoor/accessories/",
      ],
    },
  },
  {
    id: "stickley",
    name: "Stickley",
    domain: "stickley.com",
    profile: {
      asset_hosts: ["stickley.com", "cdn.stickley.com"],
      title_suffixes: ["| Stickley"],
      product_path_tokens: ["product", "products", "item"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/search?q={query}"],
    },
  },
  {
    id: "cr-laine",
    name: "CR Laine",
    domain: "crlaine.com",
    profile: {
      asset_hosts: ["crlaine.com", "cdn.crlaine.com"],
      title_suffixes: ["| CR Laine"],
      product_path_tokens: ["product", "products", "item"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/search?q={query}"],
    },
  },
  // Lee Industries — REMOVED (blocklisted, see vendor-blocklist.mjs)
  {
    id: "sherrill",
    name: "Sherrill Furniture",
    domain: "sherrillfurniture.com",
    profile: {
      asset_hosts: ["sherrillfurniture.com", "cdn.sherrillfurniture.com"],
      title_suffixes: ["| Sherrill Furniture", "| Sherrill"],
      product_path_tokens: ["catalog", "product", "products", "item"],
      reject_path_tokens: ["collections"],
      image_path_hints: ["/products/", "/images/", "/media/", "/sites/"],
    },
    discovery: {
      search_paths: ["/search?q={query}"],
      category_urls: [
        "/search-results?items_per_page=All&",
      ],
    },
  },
  {
    id: "miles-talbott",
    name: "Miles Talbott",
    domain: "www.themtcompany.com",
    profile: {
      asset_hosts: ["themtcompany.com", "www.themtcompany.com"],
      title_suffixes: ["| The MT Company", "| Miles Talbott"],
      product_path_tokens: ["detail"],
      reject_path_tokens: ["search", "collections", "fabrics", "login"],
      image_path_hints: ["/uploads/images/furniture/", "/furniture/hero/"],
    },
    discovery: {
      // AJAX-based: uses GET /inc/ajax/filter_furniture.php?category=X&limit=60&page=N&view=1
      ajax_categories: [
        "bar-and-counter-stools", "beds", "chairs", "chaises", "dining-chairs",
        "exposed-wood-chairs", "gliders", "ottomans-and-benches", "outdoor-chairs",
        "outdoor-dining-chairs", "outdoor-ottomans", "outdoor-sectional",
        "outdoor-sofas", "outdoor-swivel-chairs", "outdoor-upholstered-tables",
        "rockers", "sectional", "settees", "sleepers", "sofas",
        "swivel-chairs", "swivel-gliders", "swivel-rockers", "upholstered-tables",
      ],
      ajax_endpoint: "/inc/ajax/filter_furniture.php",
      detail_base: "/furniture/detail",
    },
  },
  {
    id: "norwalk",
    name: "Norwalk Furniture",
    domain: "norwalkfurniture.com",
    profile: {
      asset_hosts: ["norwalkfurniture.com", "www.norwalkfurniture.com"],
      title_suffixes: ["| Norwalk Furniture", "| Norwalk"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "customer", "checkout", "catalogsearch", "cms", "fabrics"],
      image_path_hints: ["/media/catalog/product/"],
    },
    discovery: {
      // Magento 2 with ?p=N&product_list_limit=100 pagination
      scraper: "norwalk-scraper.mjs",
    },
    traits: {
      com_available: true,
      customizable: true,
      made_to_order: true,
    },
  },
  {
    id: "surya",
    name: "Surya",
    domain: "surya.com",
    profile: {
      asset_hosts: ["surya.com", "suryacomsafd-cffmgqambnd5awaz.z02.azurefd.net"],
      title_suffixes: ["| Surya"],
      product_path_tokens: ["Product"],
      reject_path_tokens: ["search", "login", "cart"],
      image_path_hints: ["/Resources/", "/prod/"],
    },
    discovery: {
      // API-based: uses /api/v2/products?categoryId=X&expand=content,images,varianttraits
      api_scraper: "surya-scraper.mjs",
    },
  },
  {
    id: "verellen",
    name: "Verellen",
    domain: "verellen.biz",
    profile: {
      asset_hosts: ["verellen.biz", "magento.verellen.biz"],
      title_suffixes: ["| Verellen"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "collections", "materials-finishes"],
      image_path_hints: ["/media/catalog/product/"],
    },
    discovery: {
      graphql_endpoint: "https://magento.verellen.biz/graphql",
    },
  },
  // ── TIER 2 ──
  {
    id: "arteriors",
    name: "Arteriors",
    domain: "arteriorshome.com",
    flat_product_urls: true,
    profile: {
      asset_hosts: ["arteriorshome.com", "arteriors.com", "cdn.arteriors.com"],
      title_suffixes: ["| Arteriors"],
      product_path_tokens: ["product", "products", "item"],
      reject_path_tokens: ["search", "collections", "customer", "cms", "catalogsearch", "checkout"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/search?q={query}"],
    },
  },
  // Visual Comfort — REMOVED (blocklisted, see vendor-blocklist.mjs)
  // Surya duplicate removed — already defined above (line ~388)
  // Loloi Rugs — REMOVED (blocklisted, see vendor-blocklist.mjs)
  {
    id: "made-goods",
    name: "Made Goods",
    domain: "madegoods.com",
    profile: {
      asset_hosts: ["madegoods.com", "cdn.madegoods.com"],
      title_suffixes: ["| Made Goods"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/search?q={query}"],
    },
  },
  {
    id: "uttermost",
    name: "Uttermost",
    domain: "uttermost.com",
    flat_product_urls: true,
    profile: {
      asset_hosts: ["uttermost.com", "cdn.uttermost.com"],
      title_suffixes: ["| Uttermost"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "collections", "customer", "cms", "catalogsearch", "checkout"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
  },
  {
    id: "palecek",
    name: "Palecek",
    domain: "palecek.com",
    profile: {
      asset_hosts: ["palecek.com", "cdn.palecek.com"],
      title_suffixes: ["| Palecek"],
      product_path_tokens: ["palecek-"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
  },
  {
    id: "gabby",
    name: "Gabby",
    domain: "gabbyhome.com",
    profile: {
      asset_hosts: ["gabbyhome.com", "cdn.gabbyhome.com"],
      title_suffixes: ["| Gabby"],
      product_path_tokens: ["product", "products", "shop"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
  },
  {
    id: "noir",
    name: "Noir Furniture",
    domain: "noirfurniturela.com",
    profile: {
      asset_hosts: ["noirfurniturela.com", "cdn.noirfurniturela.com"],
      title_suffixes: ["| Noir"],
      product_path_tokens: ["product", "products", "shop"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
  },
  {
    id: "currey",
    name: "Currey & Company",
    domain: "currey.com",
    profile: {
      asset_hosts: ["currey.com", "cdn.currey.com"],
      title_suffixes: ["| Currey & Company"],
      product_path_tokens: ["product", "products", "shop"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
  },
  {
    id: "jaipur-living",
    name: "Jaipur Living",
    domain: "jaipurliving.com",
    profile: {
      asset_hosts: ["jaipurliving.com", "cdn.jaipurliving.com"],
      title_suffixes: ["| Jaipur Living"],
      product_path_tokens: ["product", "products", "shop"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
  },
  {
    id: "bungalow5",
    name: "Bungalow 5",
    domain: "bungalow5.com",
    profile: {
      asset_hosts: ["bungalow5.com", "cdn.bungalow5.com"],
      title_suffixes: ["| Bungalow 5"],
      product_path_tokens: ["product", "products", "shop"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
  },
  {
    id: "worlds-away",
    name: "Worlds Away",
    domain: "worldsaway.com",
    profile: {
      asset_hosts: ["worldsaway.com", "cdn.worldsaway.com"],
      title_suffixes: ["| Worlds Away"],
      product_path_tokens: ["product", "products", "shop"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
  },
  {
    id: "global-views",
    name: "Global Views",
    domain: "globalviews.com",
    profile: {
      asset_hosts: ["globalviews.com", "cdn.globalviews.com"],
      title_suffixes: ["| Global Views"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
  },
  {
    id: "aidan-gray",
    name: "Aidan Gray",
    domain: "aidangray.com",
    profile: {
      asset_hosts: ["aidangray.com", "cdn.aidangray.com"],
      title_suffixes: ["| Aidan Gray"],
      product_path_tokens: ["product", "products", "shop"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
  },
  // ── TIER 3 ──
  {
    id: "hancock-moore",
    name: "Hancock & Moore",
    domain: "hancockandmoore.com",
    profile: {
      asset_hosts: ["hancockandmoore.com", "cdn.hancockandmoore.com"],
      title_suffixes: ["| Hancock & Moore"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/search?q={query}"],
    },
  },
  {
    id: "riverside",
    name: "Riverside Furniture",
    domain: "riversidefurniture.com",
    profile: {
      asset_hosts: ["riversidefurniture.com", "cdn.riversidefurniture.com"],
      title_suffixes: ["| Riverside Furniture"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/search?q={query}"],
    },
  },
  {
    id: "marge-carson",
    name: "Marge Carson",
    domain: "margecarson.com",
    profile: {
      asset_hosts: ["margecarson.com", "cdn.margecarson.com"],
      title_suffixes: ["| Marge Carson"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/search?q={query}"],
    },
  },
  // ── TIER 4 ──
  {
    id: "rh-trade",
    name: "RH (Trade Program)",
    domain: "rh.com",
    profile: {
      asset_hosts: ["rh.com", "arha.scene7.com", "rhmodern.scene7.com", "cdn.rh.com"],
      title_suffixes: ["| RH", "| Restoration Hardware", " - RH"],
      product_path_tokens: ["product", "products", "catalog"],
      reject_path_tokens: ["search", "gallery", "sourcebooks", "gifts", "category"],
      image_path_hints: ["/is/image/", "/images/", "/catalog/"],
    },
    discovery: {
      search_paths: ["/search?query={query}"],
    },
  },
  // Holly Hunt — REMOVED (blocklisted, see vendor-blocklist.mjs)
  {
    id: "kravet",
    name: "Kravet Furniture",
    domain: "kravet.com",
    profile: {
      asset_hosts: ["kravet.com", "cdn.kravet.com"],
      title_suffixes: ["| Kravet"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/search?q={query}"],
    },
  },
  {
    id: "kincaid",
    name: "Kincaid",
    domain: "kincaidfurniture.com",
    profile: {
      asset_hosts: ["kincaidfurniture.com", "cdn.kincaidfurniture.com"],
      title_suffixes: ["| Kincaid"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
    discovery: {
      search_paths: ["/search?q={query}"],
    },
  },
  // ── ADDITIONAL SHOPIFY VENDORS ──
  {
    id: "jonathan-adler",
    name: "Jonathan Adler",
    domain: "jonathanadler.com",
    shopify_domain: "jonathanadler.com",
    profile: {
      asset_hosts: ["jonathanadler.com", "cdn.shopify.com"],
      title_suffixes: ["| Jonathan Adler"],
      product_path_tokens: ["products"],
      reject_path_tokens: ["search", "collections"],
    },
  },
  {
    id: "abc-home",
    name: "ABC Home",
    domain: "abchome.com",
    shopify_domain: "abchome.com",
    profile: {
      asset_hosts: ["abchome.com", "cdn.shopify.com"],
      title_suffixes: ["| ABC Home"],
      product_path_tokens: ["products"],
      reject_path_tokens: ["search", "collections"],
    },
  },
  {
    id: "jayson-home",
    name: "Jayson Home",
    domain: "jaysonhome.com",
    shopify_domain: "jaysonhome.com",
    profile: {
      asset_hosts: ["jaysonhome.com", "cdn.shopify.com"],
      title_suffixes: ["| Jayson Home"],
      product_path_tokens: ["products"],
      reject_path_tokens: ["search", "collections"],
    },
  },
  {
    id: "high-fashion-home",
    name: "High Fashion Home",
    domain: "highfashionhome.com",
    shopify_domain: "highfashionhome.com",
    profile: {
      asset_hosts: ["highfashionhome.com", "cdn.shopify.com"],
      title_suffixes: ["| High Fashion Home"],
      product_path_tokens: ["products"],
      reject_path_tokens: ["search", "collections"],
    },
  },
  {
    id: "flexsteel",
    name: "Flexsteel",
    domain: "flexsteel.com",
    shopify_domain: "flexsteel.com",
    profile: {
      asset_hosts: ["flexsteel.com", "cdn.shopify.com"],
      title_suffixes: ["| Flexsteel"],
      product_path_tokens: ["products"],
      reject_path_tokens: ["search", "collections"],
    },
  },
  {
    id: "lulu-and-georgia",
    name: "Lulu and Georgia",
    domain: "luluandgeorgia.com",
    shopify_domain: "luluandgeorgia.com",
    profile: {
      asset_hosts: ["luluandgeorgia.com", "cdn.shopify.com"],
      title_suffixes: ["| Lulu and Georgia"],
      product_path_tokens: ["products"],
      reject_path_tokens: ["search", "collections"],
    },
  },
  {
    id: "mcgee-and-co",
    name: "McGee & Co",
    domain: "mcgeeandco.com",
    shopify_domain: "mcgeeandco.com",
    profile: {
      asset_hosts: ["mcgeeandco.com", "cdn.shopify.com"],
      title_suffixes: ["| McGee & Co"],
      product_path_tokens: ["products"],
      reject_path_tokens: ["search", "collections"],
    },
  },
  {
    id: "schoolhouse",
    name: "Schoolhouse Electric",
    domain: "schoolhouseelectric.com",
    shopify_domain: "schoolhouseelectric.com",
    profile: {
      asset_hosts: ["schoolhouseelectric.com", "cdn.shopify.com"],
      title_suffixes: ["| Schoolhouse"],
      product_path_tokens: ["products"],
      reject_path_tokens: ["search", "collections"],
    },
  },
  // ── ADDITIONAL TIER 3 VENDORS ──
  {
    id: "sam-moore",
    name: "Sam Moore",
    domain: "sammoore.com",
    profile: {
      asset_hosts: ["sammoore.com"],
      title_suffixes: ["| Sam Moore"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
  },
  {
    id: "fairfield-chair",
    name: "Fairfield Chair",
    domain: "fairfieldchair.com",
    sitemap_url: "https://magento.fairfieldchair.com/media/sitemap/sitemap-1-2.xml",
    profile: {
      asset_hosts: ["fairfieldchair.com", "magento.fairfieldchair.com"],
      title_suffixes: ["| Fairfield Chair", "| Fairfield"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
      // Sitemap products are at root path (e.g., /square-56-biscuit-tuft-king-bed)
      // so we need a special flag to accept all sitemap URLs
      accept_all_sitemap_urls: true,
    },
    discovery: {
      category_urls: [
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=1",
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=2",
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=3",
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=4",
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=5",
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=6",
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=7",
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=8",
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=9",
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=10",
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=11",
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=12",
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=13",
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=14",
        "/products/residential/shop-by-room/living?sortKey=name&sortDirection=ASC&pageSize=96&page=15",
        "/products/residential/shop-by-room/bedroom?pageSize=96&page=1&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/bedroom?pageSize=96&page=2&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/dining?pageSize=96&page=1&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/dining?pageSize=96&page=2&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/dining?pageSize=96&page=3&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/dining?pageSize=96&page=4&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/dining?pageSize=96&page=5&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/dining?pageSize=96&page=6&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/dining?pageSize=96&page=7&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/dining?pageSize=96&page=8&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/dining?pageSize=96&page=9&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/dining?pageSize=96&page=10&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/dining?pageSize=96&page=11&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/dining?pageSize=96&page=12&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/dining?pageSize=96&page=13&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/dining?pageSize=96&page=14&sortKey=name&sortDirection=ASC",
        "/products/residential/shop-by-room/office?pageSize=96&page=1&sortKey=name&sortDirection=ASC",
      ],
    },
  },
  {
    id: "american-drew",
    name: "American Drew",
    domain: "americandrew.com",
    profile: {
      asset_hosts: ["americandrew.com"],
      title_suffixes: ["| American Drew"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
  },
  {
    id: "hammary",
    name: "Hammary",
    domain: "hammary.com",
    profile: {
      asset_hosts: ["hammary.com"],
      title_suffixes: ["| Hammary"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
  },
  {
    id: "thomasville",
    name: "Thomasville",
    domain: "thomasville.com",
    profile: {
      asset_hosts: ["thomasville.com"],
      title_suffixes: ["| Thomasville"],
      product_path_tokens: ["product", "products"],
      reject_path_tokens: ["search", "collections"],
      image_path_hints: ["/products/", "/images/", "/media/"],
    },
  },
];
