import { createClientFromRequest } from 'npm:@base44/sdk@0.8.20';

// ============================================================
// MASSIVE FURNITURE CATALOG — 16 Manufacturers, 160+ SKUs
// Ranges from budget (Ashley, Coaster) to ultra-luxury (Baker, Maitland-Smith)
// All descriptions are original. SKUs are platform-assigned.
// ============================================================
const CATALOG = [

  // ══════════════════════════════════════════════════════
  // ASHLEY FURNITURE — Budget/Value Leader
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Ashley Furniture",sku:"ASH-SOF-001",name:"Altari Slate Sofa",category:"sofa",style:"contemporary",material:"performance_fabric",colors_available:["slate","alloy","cream"],price_retail:599,price_wholesale_tier1:330,price_wholesale_tier2:299,price_wholesale_tier3:269,inventory_in_stock:120,inventory_in_production:200,lead_time_weeks:2,dimensions_length:88,dimensions_width:38,dimensions_height:37,dimensions_seat_height:20,weight_lbs:130,description:"A no-fuss contemporary sofa wrapped in a durable polyester upholstery that handles everyday family life. Generous seating depth and pillow-top armrests add comfort well above its price point.",features:["Polyester upholstery","Corner-blocked frame","Attached back cushions","Reversible seat cushions"],certifications:["CertiPUR-US"],rating:4.2,review_count:1820,warranty_years:1,shipping_cost:89,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},
  {manufacturer_name:"Ashley Furniture",sku:"ASH-SOF-002",name:"Darcy Cobblestone Loveseat",category:"sofa",style:"contemporary",material:"performance_fabric",colors_available:["cobblestone","java","salsa"],price_retail:449,price_wholesale_tier1:247,price_wholesale_tier2:224,price_wholesale_tier3:202,inventory_in_stock:200,inventory_in_production:300,lead_time_weeks:2,dimensions_length:65,dimensions_width:38,dimensions_height:38,dimensions_seat_height:21,weight_lbs:98,description:"A compact loveseat perfect for apartments, offices, and secondary living spaces. The plush chenille-feel fabric is soft to the touch while maintaining durability for everyday use.",features:["Tufted back","Rolled arms","Corner-blocked frame","Attached cushions"],certifications:["CertiPUR-US"],rating:4.3,review_count:2450,warranty_years:1,shipping_cost:79,thumbnail:"https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600&q=80",images:["https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80"],status:"active"},
  {manufacturer_name:"Ashley Furniture",sku:"ASH-BED-001",name:"Maribel Black King Panel Bed",category:"bed",style:"contemporary",material:"wood",colors_available:["black","dark brown","white"],price_retail:389,price_wholesale_tier1:214,price_wholesale_tier2:194,price_wholesale_tier3:175,inventory_in_stock:180,inventory_in_production:250,lead_time_weeks:2,dimensions_length:84,dimensions_width:82,dimensions_height:58,weight_lbs:140,description:"A classic panel bed with a bold molded headboard and footboard that brings formal bedroom style to an accessible price. The engineered wood construction provides excellent stability and resistance to warping.",features:["Panel headboard and footboard","Bolt-on metal side rails","Slat system included","Matching dresser available"],certifications:["CARB Phase 2"],rating:4.1,review_count:3100,warranty_years:1,shipping_cost:99,thumbnail:"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",images:["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80"],status:"active"},
  {manufacturer_name:"Ashley Furniture",sku:"ASH-DIN-001",name:"Berringer Rectangular Dining Table",category:"dining_table",style:"traditional",material:"wood",colors_available:["rustic brown","black","white"],price_retail:328,price_wholesale_tier1:180,price_wholesale_tier2:164,price_wholesale_tier3:148,inventory_in_stock:250,inventory_in_production:350,lead_time_weeks:2,dimensions_length:66,dimensions_width:38,dimensions_height:30,weight_lbs:85,description:"A family-friendly dining table with a faux stone-look tabletop and cottage-style turned legs. The easy-clean surface handles spills and sticky fingers without complaint.",features:["Faux stone tabletop","Turned legs","Seats 6","Matching chairs available"],certifications:["CARB Phase 2"],rating:4.0,review_count:1950,warranty_years:1,shipping_cost:69,thumbnail:"https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80",images:["https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"],status:"active"},
  {manufacturer_name:"Ashley Furniture",sku:"ASH-DRS-001",name:"Trinell Dresser",category:"dresser",style:"traditional",material:"wood",colors_available:["rustic brown","warm brown"],price_retail:419,price_wholesale_tier1:230,price_wholesale_tier2:209,price_wholesale_tier3:189,inventory_in_stock:160,inventory_in_production:200,lead_time_weeks:2,dimensions_length:60,dimensions_width:16,dimensions_height:36,weight_lbs:110,description:"A six-drawer dresser with a warm brown finish and a planked replicated wood grain that evokes rustic farmhouse charm. Smooth-glide drawers and clean nickel-tone pulls make it a practical everyday piece.",features:["Six smooth-glide drawers","Rustic plank look","Nickel-tone hardware","Anti-tip strap included"],certifications:["CARB Phase 2"],rating:4.2,review_count:1380,warranty_years:1,shipping_cost:79,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},
  {manufacturer_name:"Ashley Furniture",sku:"ASH-CHR-001",name:"Zinhle Accent Chair",category:"chair",style:"contemporary",material:"performance_fabric",colors_available:["taupe","teal","gray"],price_retail:289,price_wholesale_tier1:159,price_wholesale_tier2:144,price_wholesale_tier3:130,inventory_in_stock:220,inventory_in_production:300,lead_time_weeks:1,dimensions_length:31,dimensions_width:31,dimensions_height:33,dimensions_seat_height:19,weight_lbs:42,description:"A compact accent chair with a tight back and seat and a set of tapered plastic legs in a metallic finish. The straightforward design adapts to contemporary, mid-century, and transitional settings.",features:["Polyester upholstery","Tapered legs","Corner-blocked frame","Attached cushion"],certifications:["CertiPUR-US"],rating:4.0,review_count:890,warranty_years:1,shipping_cost:59,thumbnail:"https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80",images:["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80"],status:"active"},
  {manufacturer_name:"Ashley Furniture",sku:"ASH-COF-001",name:"Gerilyn Coffee Table",category:"coffee_table",style:"contemporary",material:"glass",colors_available:["chrome/glass","black/glass"],price_retail:259,price_wholesale_tier1:142,price_wholesale_tier2:129,price_wholesale_tier3:116,inventory_in_stock:180,inventory_in_production:250,lead_time_weeks:2,dimensions_length:48,dimensions_width:24,dimensions_height:17,weight_lbs:52,description:"A sleek glass-top coffee table with a sculptural chrome or black metal base. The clear tempered glass top keeps rooms feeling open, and the lower shelf provides practical storage for remotes and books.",features:["Tempered glass top","Metal pedestal base","Lower display shelf","Leveling glides"],certifications:["BIFMA"],rating:4.1,review_count:1240,warranty_years:1,shipping_cost:55,thumbnail:"https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600&q=80",images:["https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // COASTER FINE FURNITURE — Budget/Mid Value
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Coaster Fine Furniture",sku:"COA-SOF-001",name:"Weir Casual Sofa",category:"sofa",style:"transitional",material:"performance_fabric",colors_available:["dark grey","beige","brown"],price_retail:699,price_wholesale_tier1:385,price_wholesale_tier2:349,price_wholesale_tier3:315,inventory_in_stock:100,inventory_in_production:150,lead_time_weeks:3,dimensions_length:86,dimensions_width:37,dimensions_height:36,dimensions_seat_height:19,weight_lbs:125,description:"A transitional sofa with pillow-top arms and a semi-attached back that bridges casual and formal living room styles. The microfiber upholstery is soft and stain-resistant.",features:["Microfiber upholstery","Pillow-top arms","Sinuous spring suspension","Removable back cushions"],certifications:["CertiPUR-US"],rating:4.1,review_count:740,warranty_years:1,shipping_cost:95,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},
  {manufacturer_name:"Coaster Fine Furniture",sku:"COA-BED-001",name:"Sandy Beach King Sleigh Bed",category:"bed",style:"traditional",material:"wood",colors_available:["white","dark cherry","brown"],price_retail:549,price_wholesale_tier1:302,price_wholesale_tier2:274,price_wholesale_tier3:247,inventory_in_stock:80,inventory_in_production:120,lead_time_weeks:3,dimensions_length:84,dimensions_width:82,dimensions_height:54,weight_lbs:160,description:"A classic sleigh bed silhouette in a crisp white finish that anchors coastal, cottage, and farmhouse bedrooms. The curved headboard and footboard add a graceful formality without feeling heavy.",features:["Curved sleigh profile","Engineered wood construction","Metal center rail","Slat system included"],certifications:["CARB Phase 2"],rating:4.2,review_count:660,warranty_years:1,shipping_cost:110,thumbnail:"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",images:["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80"],status:"active"},
  {manufacturer_name:"Coaster Fine Furniture",sku:"COA-DIN-001",name:"Nora Round Dining Table",category:"dining_table",style:"modern",material:"wood",colors_available:["white","black","natural walnut"],price_retail:389,price_wholesale_tier1:214,price_wholesale_tier2:194,price_wholesale_tier3:175,inventory_in_stock:140,inventory_in_production:200,lead_time_weeks:3,dimensions_length:48,dimensions_width:48,dimensions_height:30,weight_lbs:75,description:"A round dining table with a smooth pedestal base that maximizes floor space while seating four comfortably. The clean lines adapt to modern, Scandi, and transitional dining rooms.",features:["Round top","Pedestal base","Seats 4","Easy assembly"],certifications:["CARB Phase 2"],rating:4.1,review_count:520,warranty_years:1,shipping_cost:65,thumbnail:"https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80",images:["https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"],status:"active"},
  {manufacturer_name:"Coaster Fine Furniture",sku:"COA-BSH-001",name:"Stonebridge Bookcase",category:"bookshelf",style:"transitional",material:"wood",colors_available:["antique white","warm brown"],price_retail:299,price_wholesale_tier1:164,price_wholesale_tier2:149,price_wholesale_tier3:134,inventory_in_stock:200,inventory_in_production:250,lead_time_weeks:2,dimensions_length:36,dimensions_width:12,dimensions_height:72,weight_lbs:75,description:"A versatile standard bookcase with five adjustable shelves and crown molding detailing that dresses up any home library, office, or bedroom. The closed back keeps displays tidy.",features:["5 adjustable shelves","Crown molding","Closed back","Anti-tip bracket included"],certifications:["CARB Phase 2"],rating:4.2,review_count:890,warranty_years:1,shipping_cost:59,thumbnail:"https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&q=80",images:["https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // STEVE SILVER — Budget/Mid Value
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Steve Silver",sku:"SSF-DIN-001",name:"Matinee Counter Height Table",category:"dining_table",style:"industrial",material:"wood",colors_available:["antique oak","dark espresso"],price_retail:420,price_wholesale_tier1:231,price_wholesale_tier2:210,price_wholesale_tier3:189,inventory_in_stock:95,inventory_in_production:140,lead_time_weeks:3,dimensions_length:60,dimensions_width:36,dimensions_height:36,weight_lbs:95,description:"A counter-height dining table with a solid pine top and metal pipe-style legs that bring industrial farmhouse character to kitchens and dining rooms. Pairs with matching bar stools for a cohesive look.",features:["Solid pine top","Metal pipe legs","Counter height","Matching stools available"],certifications:["CARB Phase 2"],rating:4.2,review_count:480,warranty_years:1,shipping_cost:75,thumbnail:"https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80",images:["https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"],status:"active"},
  {manufacturer_name:"Steve Silver",sku:"SSF-COF-001",name:"Hamlyn Coffee Table",category:"coffee_table",style:"industrial",material:"wood",colors_available:["vintage oak","dark espresso"],price_retail:289,price_wholesale_tier1:159,price_wholesale_tier2:144,price_wholesale_tier3:130,inventory_in_stock:130,inventory_in_production:180,lead_time_weeks:3,dimensions_length:50,dimensions_width:26,dimensions_height:18,weight_lbs:68,description:"A sturdy rectangular coffee table with a plank-style pine top and an industrial X-metal base. The lower shelf doubles as display and storage space, making it as functional as it is stylish.",features:["Pine plank top","Industrial X-base","Lower shelf","Leveling glides"],certifications:["CARB Phase 2"],rating:4.1,review_count:610,warranty_years:1,shipping_cost:65,thumbnail:"https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600&q=80",images:["https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // JOFRAN — Mid-Range Value
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Jofran",sku:"JFR-DIN-001",name:"Simplicity Dining Table",category:"dining_table",style:"scandinavian",material:"wood",colors_available:["natural pine","espresso","white"],price_retail:699,price_wholesale_tier1:385,price_wholesale_tier2:349,price_wholesale_tier3:315,inventory_in_stock:75,inventory_in_production:100,lead_time_weeks:4,dimensions_length:72,dimensions_width:36,dimensions_height:30,weight_lbs:95,description:"A minimalist dining table with a solid pine top and straight tapered legs that channel Nordic simplicity. The clean proportions make it the perfect canvas for any dining chair style.",features:["Solid pine top","Tapered legs","Seats 6","Extension leaf optional"],certifications:["FSC Certified","CARB Phase 2"],rating:4.3,review_count:380,warranty_years:2,shipping_cost:95,thumbnail:"https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80",images:["https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"],status:"active"},
  {manufacturer_name:"Jofran",sku:"JFR-BSH-001",name:"Madison County Bookcase",category:"bookshelf",style:"traditional",material:"wood",colors_available:["vintage oak","barnwood"],price_retail:520,price_wholesale_tier1:286,price_wholesale_tier2:260,price_wholesale_tier3:234,inventory_in_stock:60,inventory_in_production:80,lead_time_weeks:4,dimensions_length:36,dimensions_width:14,dimensions_height:77,weight_lbs:90,description:"A tall bookcase finished in a vintage barnwood that recalls the weathered wood of American farmhouses. Five shelves, two of which are adjustable, accommodate books, plants, and decorative objects.",features:["5 shelves","2 adjustable","Barnwood finish","Anti-tip hardware"],certifications:["CARB Phase 2"],rating:4.4,review_count:290,warranty_years:2,shipping_cost:75,thumbnail:"https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&q=80",images:["https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // BERNHARDT — Upper-Mid / Luxury
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Bernhardt",sku:"BRN-SOF-001",name:"Cantor Upholstered Sofa",category:"sofa",style:"contemporary",material:"performance_fabric",colors_available:["stone","charcoal","ivory","navy"],price_retail:3890,price_wholesale_tier1:2140,price_wholesale_tier2:1945,price_wholesale_tier3:1750,inventory_in_stock:24,inventory_in_production:40,lead_time_weeks:8,dimensions_length:88,dimensions_width:36,dimensions_height:32,dimensions_seat_height:18,weight_lbs:145,description:"A generously proportioned sofa featuring track arms and a deep seat for superior lounging comfort. Crafted with a kiln-dried hardwood frame and wrapped in durable performance fabric that resists stains and fading.",features:["Kiln-dried hardwood frame","High-resilience foam cushions","Removable back cushions","8-way hand-tied springs"],certifications:["BIFMA","CertiPUR-US"],rating:4.7,review_count:89,warranty_years:3,shipping_cost:295,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},
  {manufacturer_name:"Bernhardt",sku:"BRN-SOF-002",name:"Linea Track Arm Sofa",category:"sofa",style:"modern",material:"linen",colors_available:["natural","dove","slate","blush"],price_retail:4250,price_wholesale_tier1:2340,price_wholesale_tier2:2120,price_wholesale_tier3:1900,inventory_in_stock:18,inventory_in_production:30,lead_time_weeks:10,dimensions_length:92,dimensions_width:38,dimensions_height:30,dimensions_seat_height:17,weight_lbs:160,description:"Clean-lined modern sofa with minimal track arms and a refined silhouette. Belgian linen upholstery adds an elevated texture while maintaining a neutral palette suitable for any interior.",features:["Solid maple frame","Belgian linen upholstery","Down-blend cushion wrap","Adjustable leg height"],certifications:["BIFMA","Greenguard Gold"],rating:4.5,review_count:64,warranty_years:5,shipping_cost:320,thumbnail:"https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600&q=80",images:["https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80"],status:"active"},
  {manufacturer_name:"Bernhardt",sku:"BRN-CHR-001",name:"Haven Lounge Chair",category:"chair",style:"transitional",material:"velvet",colors_available:["emerald","navy","dusty rose","camel","graphite"],price_retail:1980,price_wholesale_tier1:1090,price_wholesale_tier2:990,price_wholesale_tier3:890,inventory_in_stock:42,inventory_in_production:20,lead_time_weeks:6,dimensions_length:34,dimensions_width:34,dimensions_height:31,dimensions_seat_height:19,weight_lbs:58,description:"An inviting lounge chair with a gently curved back and wide seat that cradles you in comfort. Premium velvet upholstery in a range of rich jewel tones makes it the perfect accent piece.",features:["Swivel base option available","Down-wrap cushion","Solid walnut legs","COM available"],certifications:["CertiPUR-US"],rating:4.8,review_count:113,warranty_years:3,shipping_cost:175,thumbnail:"https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80",images:["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80"],status:"active"},
  {manufacturer_name:"Bernhardt",sku:"BRN-CHR-002",name:"Interiors Swivel Chair",category:"chair",style:"mid_century",material:"leather",colors_available:["cognac","white","black","caramel"],price_retail:2400,price_wholesale_tier1:1320,price_wholesale_tier2:1200,price_wholesale_tier3:1080,inventory_in_stock:28,inventory_in_production:15,lead_time_weeks:8,dimensions_length:32,dimensions_width:33,dimensions_height:32,dimensions_seat_height:17,weight_lbs:62,description:"A sleek mid-century inspired swivel chair upholstered in premium semi-aniline leather with a five-star polished chrome base. The low profile and wide seat make it as comfortable as it is beautiful.",features:["Semi-aniline leather","360° swivel","Polished chrome base","High-resilience foam seat"],certifications:["Leather Working Group Silver","CertiPUR-US"],rating:4.8,review_count:76,warranty_years:5,shipping_cost:195,thumbnail:"https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&q=80",images:["https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80"],status:"active"},
  {manufacturer_name:"Bernhardt",sku:"BRN-BED-001",name:"Clarendon Upholstered Platform Bed",category:"bed",style:"contemporary",material:"linen",colors_available:["cloud","pewter","sand","midnight"],price_retail:3200,price_wholesale_tier1:1760,price_wholesale_tier2:1600,price_wholesale_tier3:1440,inventory_in_stock:15,inventory_in_production:25,lead_time_weeks:10,dimensions_length:88,dimensions_width:86,dimensions_height:48,weight_lbs:210,description:"A substantial platform bed with a tall upholstered headboard that anchors any master bedroom. The low profile frame eliminates the need for a box spring while the wide legs add a sculptural quality.",features:["No box spring required","Adjustable slat system","USB charging ports in headboard","Available in Queen and King"],certifications:["BIFMA","Greenguard Gold"],rating:4.6,review_count:77,warranty_years:5,shipping_cost:450,thumbnail:"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",images:["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80"],status:"active"},
  {manufacturer_name:"Bernhardt",sku:"BRN-DIN-001",name:"Tradewinds Dining Table",category:"dining_table",style:"transitional",material:"wood",colors_available:["dark walnut","light oak","ebony"],price_retail:2800,price_wholesale_tier1:1540,price_wholesale_tier2:1400,price_wholesale_tier3:1260,inventory_in_stock:10,inventory_in_production:20,lead_time_weeks:8,dimensions_length:84,dimensions_width:42,dimensions_height:30,weight_lbs:185,description:"A classic rectangular dining table crafted from solid American walnut with a hand-applied finish. The trestle base provides leg room without sacrificing visual weight, ideal for seats of six to eight.",features:["Solid American walnut","Extension leaf option adds 20\"","Hand-applied finish","Seats 6-8"],certifications:["FSC Certified Wood"],rating:4.7,review_count:55,warranty_years:5,shipping_cost:380,thumbnail:"https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80",images:["https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"],status:"active"},
  {manufacturer_name:"Bernhardt",sku:"BRN-DSK-001",name:"Brizo Writing Desk",category:"desk",style:"modern",material:"wood",colors_available:["matte white","dark walnut","ash gray"],price_retail:2600,price_wholesale_tier1:1430,price_wholesale_tier2:1300,price_wholesale_tier3:1170,inventory_in_stock:14,inventory_in_production:18,lead_time_weeks:9,dimensions_length:60,dimensions_width:26,dimensions_height:30,weight_lbs:110,description:"A minimalist writing desk with a floating top appearance and a waterfall edge in lacquered wood. A single pencil drawer and integrated cable port keep the surface clean and organized.",features:["Lacquered wood top","Floating appearance","Pencil drawer","Integrated cable port"],certifications:["BIFMA","Greenguard Gold"],rating:4.6,review_count:42,warranty_years:5,shipping_cost:280,thumbnail:"https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80",images:["https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // FOUR HANDS — Upper-Mid
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Four Hands",sku:"FH-SOF-001",name:"Atwood Modular Sectional",category:"sectional",style:"modern",material:"performance_fabric",colors_available:["cognac","storm","pebble","black"],price_retail:5600,price_wholesale_tier1:3080,price_wholesale_tier2:2800,price_wholesale_tier3:2520,inventory_in_stock:8,inventory_in_production:30,lead_time_weeks:8,dimensions_length:120,dimensions_width:95,dimensions_height:29,dimensions_seat_height:16,weight_lbs:310,description:"A modular sectional built for modern living rooms that demand both flexibility and comfort. Individual pieces connect magnetically so layouts can be reconfigured whenever your space evolves.",features:["Modular magnetic connection","Performance fabric","Low profile","Reversible chaise"],certifications:["CertiPUR-US","BIFMA"],rating:4.8,review_count:142,warranty_years:3,shipping_cost:550,thumbnail:"https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=600&q=80",images:["https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=800&q=80"],status:"active"},
  {manufacturer_name:"Four Hands",sku:"FH-SOF-002",name:"Colt Full-Grain Leather Sofa",category:"sofa",style:"industrial",material:"leather",colors_available:["tobacco","black","cognac","vintage white"],price_retail:4800,price_wholesale_tier1:2640,price_wholesale_tier2:2400,price_wholesale_tier3:2160,inventory_in_stock:14,inventory_in_production:18,lead_time_weeks:7,dimensions_length:86,dimensions_width:38,dimensions_height:34,dimensions_seat_height:19,weight_lbs:175,description:"A rugged yet refined leather sofa with a nailhead trim perimeter and visible stitching that nods to classic American craftsmanship. Full-grain leather develops a beautiful patina over time.",features:["Full-grain leather","Nailhead trim","Solid oak legs","Down-blend cushion"],certifications:["Leather Working Group Gold"],rating:4.9,review_count:201,warranty_years:5,shipping_cost:340,thumbnail:"https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=600&q=80",images:["https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800&q=80"],status:"active"},
  {manufacturer_name:"Four Hands",sku:"FH-SOF-003",name:"Yelena Performance Sofa",category:"sofa",style:"contemporary",material:"performance_fabric",colors_available:["snow","olive","taupe"],price_retail:2999,price_wholesale_tier1:1649,price_wholesale_tier2:1499,price_wholesale_tier3:1349,inventory_in_stock:32,inventory_in_production:50,lead_time_weeks:5,dimensions_length:85,dimensions_width:37,dimensions_height:32,dimensions_seat_height:18,weight_lbs:145,description:"A straight-lined contemporary sofa upholstered in Crypton performance fabric, engineered to resist moisture and bacteria. The loose back cushions and semi-attached seat cushions balance comfort and precision.",features:["Crypton performance fabric","Loose back cushions","Kiln-dried hardwood frame","Available in 3 widths"],certifications:["CertiPUR-US","BIFMA"],rating:4.7,review_count:168,warranty_years:3,shipping_cost:295,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},
  {manufacturer_name:"Four Hands",sku:"FH-TAB-001",name:"Hughes Iron & Glass Coffee Table",category:"coffee_table",style:"industrial",material:"metal",colors_available:["aged brass","matte black","antique nickel"],price_retail:1450,price_wholesale_tier1:798,price_wholesale_tier2:725,price_wholesale_tier3:653,inventory_in_stock:35,inventory_in_production:50,lead_time_weeks:5,dimensions_length:48,dimensions_width:26,dimensions_height:17,weight_lbs:85,description:"An industrial-inspired coffee table with a forged iron base and a tempered glass top. The open lower shelf provides additional display space while keeping visual weight to a minimum.",features:["Tempered glass top","Powder-coated iron base","Lower storage shelf","Leveling glides"],certifications:["BIFMA"],rating:4.6,review_count:98,warranty_years:2,shipping_cost:195,thumbnail:"https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600&q=80",images:["https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80"],status:"active"},
  {manufacturer_name:"Four Hands",sku:"FH-TAB-002",name:"Emmett Mango Wood Coffee Table",category:"coffee_table",style:"bohemian",material:"wood",colors_available:["natural mango","dark honey"],price_retail:1199,price_wholesale_tier1:659,price_wholesale_tier2:599,price_wholesale_tier3:539,inventory_in_stock:42,inventory_in_production:35,lead_time_weeks:5,dimensions_length:54,dimensions_width:30,dimensions_height:16,weight_lbs:80,description:"A live-edge inspired coffee table crafted from solid mango wood with a smooth oil-rubbed finish. Each table is unique due to the natural character of the wood — knots, grain variation, and color shifts are all part of its charm.",features:["Solid mango wood","Live-edge inspired profile","Hand-rubbed oil finish","Natural variations expected"],certifications:["FSC Certified"],rating:4.7,review_count:122,warranty_years:3,shipping_cost:185,thumbnail:"https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600&q=80",images:["https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80"],status:"active"},
  {manufacturer_name:"Four Hands",sku:"FH-CHR-001",name:"Westgate Handwoven Rattan Chair",category:"chair",style:"bohemian",material:"rattan",colors_available:["natural","whitewash","dark stain"],price_retail:1100,price_wholesale_tier1:605,price_wholesale_tier2:550,price_wholesale_tier3:495,inventory_in_stock:28,inventory_in_production:40,lead_time_weeks:6,dimensions_length:30,dimensions_width:32,dimensions_height:34,dimensions_seat_height:18,weight_lbs:38,description:"A handwoven rattan accent chair that brings organic warmth to any room. Each chair is individually handcrafted by artisans, ensuring slight variations that make each piece uniquely beautiful.",features:["Hand-woven rattan","Included cushion","Indoor/outdoor safe","Foldable"],certifications:["Rainforest Alliance"],rating:4.5,review_count:76,warranty_years:2,shipping_cost:145,thumbnail:"https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600&q=80",images:["https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80"],status:"active"},
  {manufacturer_name:"Four Hands",sku:"FH-CHR-002",name:"Augustine Swivel Chair",category:"chair",style:"contemporary",material:"performance_fabric",colors_available:["nomad taupe","sapphire navy","black","olive"],price_retail:1249,price_wholesale_tier1:687,price_wholesale_tier2:624,price_wholesale_tier3:562,inventory_in_stock:48,inventory_in_production:60,lead_time_weeks:4,dimensions_length:31,dimensions_width:31,dimensions_height:32,dimensions_seat_height:18,weight_lbs:44,description:"A versatile swivel chair with a gentle barrel back and a performance fabric that shrugs off household wear. At home in living rooms, reading nooks, and office spaces alike.",features:["360° swivel","Performance fabric","Welted seams","5-star base"],certifications:["CertiPUR-US","BIFMA"],rating:4.7,review_count:210,warranty_years:3,shipping_cost:155,thumbnail:"https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&q=80",images:["https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80"],status:"active"},
  {manufacturer_name:"Four Hands",sku:"FH-BED-001",name:"Stonington Mango Wood Bed",category:"bed",style:"mid_century",material:"wood",colors_available:["warm walnut","whitewash","ebony"],price_retail:2600,price_wholesale_tier1:1430,price_wholesale_tier2:1300,price_wholesale_tier3:1170,inventory_in_stock:20,inventory_in_production:15,lead_time_weeks:6,dimensions_length:86,dimensions_width:84,dimensions_height:42,weight_lbs:165,description:"A mid-century inspired platform bed with a slatted headboard and tapered legs that feel both familiar and fresh. Solid mango wood construction gives it substance without feeling heavy.",features:["Solid mango wood","Slatted headboard","No box spring needed","Available Queen and King"],certifications:["FSC Certified"],rating:4.7,review_count:88,warranty_years:3,shipping_cost:380,thumbnail:"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&q=80",images:["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80"],status:"active"},
  {manufacturer_name:"Four Hands",sku:"FH-DIN-001",name:"Matthes Console Dining Table",category:"dining_table",style:"industrial",material:"wood",colors_available:["dark aged oak","light oak"],price_retail:1799,price_wholesale_tier1:989,price_wholesale_tier2:899,price_wholesale_tier3:809,inventory_in_stock:25,inventory_in_production:30,lead_time_weeks:6,dimensions_length:72,dimensions_width:36,dimensions_height:30,weight_lbs:130,description:"A dining table built around a reclaimed-look solid pine top mounted on a black powder-coated iron base. The marriage of warm wood and cool metal appeals to industrial, loft, and transitional dining rooms.",features:["Solid pine top","Iron base","Seats 6","Distressed finish"],certifications:["FSC Certified","BIFMA"],rating:4.6,review_count:95,warranty_years:3,shipping_cost:265,thumbnail:"https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80",images:["https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"],status:"active"},
  {manufacturer_name:"Four Hands",sku:"FH-OUT-001",name:"Solano Outdoor Sectional",category:"outdoor",style:"contemporary",material:"performance_fabric",colors_available:["natural teak","dark teak"],price_retail:6800,price_wholesale_tier1:3740,price_wholesale_tier2:3400,price_wholesale_tier3:3060,inventory_in_stock:6,inventory_in_production:20,lead_time_weeks:10,dimensions_length:130,dimensions_width:90,dimensions_height:30,dimensions_seat_height:16,weight_lbs:280,description:"A generously proportioned outdoor sectional with a teak frame and Sunbrella cushions rated for years of sun, rain, and salt air. Modular configuration allows it to fit any patio or terrace layout.",features:["Teak frame","Sunbrella cushions","Modular design","All-weather hardware"],certifications:["Rainforest Alliance","Oeko-Tex"],rating:4.8,review_count:54,warranty_years:3,shipping_cost:650,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // ARTERIORS — Designer Luxury
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Arteriors",sku:"ART-LGT-001",name:"Navarro Cluster Chandelier",category:"lighting",style:"transitional",material:"metal",colors_available:["antique brass","oil-rubbed bronze","polished nickel"],price_retail:2200,price_wholesale_tier1:1210,price_wholesale_tier2:1100,price_wholesale_tier3:990,inventory_in_stock:18,inventory_in_production:12,lead_time_weeks:10,dimensions_length:30,dimensions_width:30,dimensions_height:26,weight_lbs:22,description:"A striking cluster chandelier featuring hand-blown glass globes suspended from a hand-forged metal armature. Each sphere captures light differently, creating a warm ambient glow across dining rooms and entryways.",features:["Hand-blown glass","Adjustable chain","Dimmable","Hardwired"],certifications:["UL Listed","ETL Listed"],rating:4.8,review_count:61,warranty_years:2,shipping_cost:125,thumbnail:"https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=600&q=80",images:["https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&q=80"],status:"active"},
  {manufacturer_name:"Arteriors",sku:"ART-LGT-002",name:"Fulton Industrial Table Lamp",category:"lighting",style:"industrial",material:"metal",colors_available:["matte black","antiqued gold","silver leaf"],price_retail:680,price_wholesale_tier1:374,price_wholesale_tier2:340,price_wholesale_tier3:306,inventory_in_stock:45,inventory_in_production:30,lead_time_weeks:8,dimensions_length:14,dimensions_width:14,dimensions_height:28,weight_lbs:8,description:"A bold table lamp with a ribbed metal body and a wide cone shade that casts generous pools of light. Industrial aesthetics are softened by warm metallic finishes that complement any interior style.",features:["Ribbed metal body","Drum shade included","3-way socket","150W max"],certifications:["UL Listed"],rating:4.5,review_count:47,warranty_years:2,shipping_cost:65,thumbnail:"https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",images:["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80"],status:"active"},
  {manufacturer_name:"Arteriors",sku:"ART-LGT-003",name:"Volta Pendant Light",category:"lighting",style:"contemporary",material:"glass",colors_available:["clear","smoked","amber"],price_retail:890,price_wholesale_tier1:490,price_wholesale_tier2:445,price_wholesale_tier3:400,inventory_in_stock:35,inventory_in_production:25,lead_time_weeks:8,dimensions_length:10,dimensions_width:10,dimensions_height:12,weight_lbs:4,description:"A modern globe pendant featuring a hand-blown glass shade with a subtle ripple texture that scatters light beautifully. Available in three colorways to suit minimalist, warm, and moody interiors.",features:["Hand-blown glass","Adjustable stem","Canopy included","E26 socket"],certifications:["UL Listed"],rating:4.7,review_count:88,warranty_years:2,shipping_cost:45,thumbnail:"https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=600&q=80",images:["https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&q=80"],status:"active"},
  {manufacturer_name:"Arteriors",sku:"ART-CHR-001",name:"Cowen Barrel Occasional Chair",category:"chair",style:"contemporary",material:"velvet",colors_available:["champagne","sage","terracotta","charcoal"],price_retail:1850,price_wholesale_tier1:1018,price_wholesale_tier2:925,price_wholesale_tier3:833,inventory_in_stock:22,inventory_in_production:15,lead_time_weeks:12,dimensions_length:29,dimensions_width:31,dimensions_height:35,dimensions_seat_height:18,weight_lbs:52,description:"An elevated occasional chair with a barrel-back profile upholstered in plush velvet and set on polished brass legs. The sculptural form is as much an art piece as it is functional seating.",features:["Solid beech frame","Polished brass legs","Tight seat and back","COM available"],certifications:["Greenguard Gold"],rating:4.7,review_count:39,warranty_years:2,shipping_cost:180,thumbnail:"https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&q=80",images:["https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80"],status:"active"},
  {manufacturer_name:"Arteriors",sku:"ART-TAB-001",name:"Aldridge Marble Side Table",category:"table",style:"transitional",material:"marble",colors_available:["white marble","black marble","travertine"],price_retail:1200,price_wholesale_tier1:660,price_wholesale_tier2:600,price_wholesale_tier3:540,inventory_in_stock:30,inventory_in_production:20,lead_time_weeks:10,dimensions_length:18,dimensions_width:18,dimensions_height:24,weight_lbs:45,description:"A refined side table pairing a natural stone top with a slender metal pedestal base. Every piece of marble is unique, displaying its own veining pattern.",features:["Natural marble top","Powder-coated iron base","Felt base pads","Unique veining"],certifications:["BIFMA"],rating:4.6,review_count:52,warranty_years:2,shipping_cost:120,thumbnail:"https://images.unsplash.com/photo-1581428982868-e410dd047a90?w=600&q=80",images:["https://images.unsplash.com/photo-1581428982868-e410dd047a90?w=800&q=80"],status:"active"},
  {manufacturer_name:"Arteriors",sku:"ART-RUG-001",name:"Cassius Hand-Knotted Rug 8x10",category:"rug",style:"transitional",material:"wool",colors_available:["ivory/camel","charcoal/ivory","rust/cream"],price_retail:2800,price_wholesale_tier1:1540,price_wholesale_tier2:1400,price_wholesale_tier3:1260,inventory_in_stock:12,inventory_in_production:20,lead_time_weeks:14,dimensions_length:120,dimensions_width:96,dimensions_height:1,weight_lbs:48,description:"A hand-knotted wool rug crafted in India by generational artisans using vegetable-dyed yarns. The subtle geometric pattern reads as understated luxury, anchoring high-design living and dining rooms.",features:["Hand-knotted wool","Vegetable-dyed yarns","8x10 standard size","Custom sizes available"],certifications:["Oeko-Tex","GoodWeave"],rating:4.8,review_count:31,warranty_years:2,shipping_cost:150,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // HOOKER FURNITURE — Upper-Mid
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Hooker Furniture",sku:"HKR-DSK-001",name:"Latitude Height-Adjustable Desk",category:"desk",style:"contemporary",material:"wood",colors_available:["light oak","dark walnut","white"],price_retail:2100,price_wholesale_tier1:1155,price_wholesale_tier2:1050,price_wholesale_tier3:945,inventory_in_stock:20,inventory_in_production:25,lead_time_weeks:8,dimensions_length:60,dimensions_width:28,dimensions_height:30,weight_lbs:140,description:"A height-adjustable standing desk with a solid wood top and a whisper-quiet dual-motor frame. Programmable height presets let multiple users save their preferred positions.",features:["Dual-motor lift","4-position memory","Cable management","300 lb capacity"],certifications:["BIFMA","Greenguard Gold"],rating:4.8,review_count:156,warranty_years:5,shipping_cost:280,thumbnail:"https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80",images:["https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80"],status:"active"},
  {manufacturer_name:"Hooker Furniture",sku:"HKR-BSH-001",name:"Waverly 84\" Wall Bookcase",category:"bookshelf",style:"traditional",material:"wood",colors_available:["medium oak","antique cherry","painted white"],price_retail:1600,price_wholesale_tier1:880,price_wholesale_tier2:800,price_wholesale_tier3:720,inventory_in_stock:16,inventory_in_production:20,lead_time_weeks:7,dimensions_length:36,dimensions_width:14,dimensions_height:84,weight_lbs:120,description:"A full-height bookcase with graduated shelving, glass-front upper doors, and solid wood drawers at the base. Designed to integrate with other Waverly pieces for a built-in look.",features:["Adjustable shelves","Glass-front upper cabinet","Soft-close drawers","Anti-tip anchor included"],certifications:["BIFMA","Greenguard"],rating:4.7,review_count:82,warranty_years:5,shipping_cost:210,thumbnail:"https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&q=80",images:["https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80"],status:"active"},
  {manufacturer_name:"Hooker Furniture",sku:"HKR-DRS-001",name:"Retreat Six-Drawer Dresser",category:"dresser",style:"transitional",material:"wood",colors_available:["coastal white","driftwood","midnight navy"],price_retail:1850,price_wholesale_tier1:1018,price_wholesale_tier2:925,price_wholesale_tier3:833,inventory_in_stock:12,inventory_in_production:18,lead_time_weeks:9,dimensions_length:64,dimensions_width:19,dimensions_height:38,weight_lbs:175,description:"A six-drawer dresser with solid wood construction and polished nickel hardware. Curved drawer fronts and tapered legs give it a transitional character that works in classic and modern bedrooms.",features:["Six smooth-glide drawers","Soft-close system","Cedar-lined bottom drawer","Mirror add-on available"],certifications:["BIFMA","CertiPUR-US"],rating:4.6,review_count:61,warranty_years:5,shipping_cost:295,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},
  {manufacturer_name:"Hooker Furniture",sku:"HKR-DIN-001",name:"Corsair Pedestal Dining Table",category:"dining_table",style:"traditional",material:"wood",colors_available:["mahogany","fruitwood","black"],price_retail:3400,price_wholesale_tier1:1870,price_wholesale_tier2:1700,price_wholesale_tier3:1530,inventory_in_stock:8,inventory_in_production:15,lead_time_weeks:10,dimensions_length:96,dimensions_width:44,dimensions_height:30,weight_lbs:220,description:"A formal dining table with a double-pedestal base and butterfly extension leaf that seats up to ten. The richly grained solid wood surface is hand-rubbed with a glaze that brings out natural wood character.",features:["Double pedestal base","20\" butterfly leaf","Seats 8-10","Felt-lined leaf storage"],certifications:["FSC Certified"],rating:4.8,review_count:44,warranty_years:5,shipping_cost:420,thumbnail:"https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80",images:["https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"],status:"active"},
  {manufacturer_name:"Hooker Furniture",sku:"HKR-SOF-001",name:"Melange Velvet Sofa",category:"sofa",style:"traditional",material:"velvet",colors_available:["deep burgundy","forest green","midnight blue","ivory"],price_retail:3100,price_wholesale_tier1:1705,price_wholesale_tier2:1550,price_wholesale_tier3:1395,inventory_in_stock:18,inventory_in_production:22,lead_time_weeks:8,dimensions_length:86,dimensions_width:37,dimensions_height:36,dimensions_seat_height:19,weight_lbs:155,description:"A traditional rolled-arm sofa upholstered in a plush multi-tone velvet that shifts in color as light plays across the surface. The carved exposed wood legs and tuxedo silhouette give it a formal yet accessible character.",features:["Multi-tone velvet","Carved exposed legs","8-way hand-tied springs","Down-blend back cushions"],certifications:["CertiPUR-US","Greenguard Gold"],rating:4.7,review_count:58,warranty_years:5,shipping_cost:310,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // CARACOLE — Luxury / Statement
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Caracole",sku:"CAR-BED-001",name:"Sophistication Channel-Tufted King Bed",category:"bed",style:"contemporary",material:"velvet",colors_available:["soft silver","dusty taupe","midnight blue","champagne"],price_retail:5800,price_wholesale_tier1:3190,price_wholesale_tier2:2900,price_wholesale_tier3:2610,inventory_in_stock:6,inventory_in_production:12,lead_time_weeks:14,dimensions_length:88,dimensions_width:88,dimensions_height:60,weight_lbs:280,description:"A luxury king bed with a curved channel-tufted headboard that rises dramatically to create a focal point worthy of a high-end hotel suite. The mirrored base reflects light to amplify the room.",features:["Channel-tufted headboard","Mirrored base panels","Integrated LED nightlight","Available Queen and King"],certifications:["Greenguard Gold","CertiPUR-US"],rating:4.9,review_count:38,warranty_years:3,shipping_cost:650,thumbnail:"https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=600&q=80",images:["https://images.unsplash.com/photo-1615874959474-d609969a20ed?w=800&q=80"],status:"active"},
  {manufacturer_name:"Caracole",sku:"CAR-DRS-001",name:"Classic Remix Lacquer Dresser",category:"dresser",style:"contemporary",material:"wood",colors_available:["silver leaf","gold leaf","ebony"],price_retail:4200,price_wholesale_tier1:2310,price_wholesale_tier2:2100,price_wholesale_tier3:1890,inventory_in_stock:8,inventory_in_production:10,lead_time_weeks:16,dimensions_length:62,dimensions_width:20,dimensions_height:36,weight_lbs:195,description:"A showstopping dresser with a lacquered case and geometric metal overlay hardware that makes it as much a sculptural object as storage.",features:["High-gloss lacquer","Geometric metal pulls","Soft-close drawers","Anti-tip hardware"],certifications:["Greenguard Gold"],rating:4.8,review_count:29,warranty_years:3,shipping_cost:480,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},
  {manufacturer_name:"Caracole",sku:"CAR-CHR-001",name:"Luxe Glam Swivel Chair",category:"chair",style:"contemporary",material:"velvet",colors_available:["ivory","blush","deep teal","black"],price_retail:2800,price_wholesale_tier1:1540,price_wholesale_tier2:1400,price_wholesale_tier3:1260,inventory_in_stock:14,inventory_in_production:12,lead_time_weeks:14,dimensions_length:32,dimensions_width:33,dimensions_height:37,dimensions_seat_height:19,weight_lbs:68,description:"A fully upholstered swivel chair with a tufted back and padded arms that evoke old Hollywood glamour with a contemporary twist.",features:["360° swivel","Button-tufted back","Polished chrome base","Down-blend cushion"],certifications:["Greenguard Gold","CertiPUR-US"],rating:4.9,review_count:52,warranty_years:3,shipping_cost:220,thumbnail:"https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80",images:["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80"],status:"active"},
  {manufacturer_name:"Caracole",sku:"CAR-SOF-001",name:"Modern Edit Performance Sofa",category:"sofa",style:"contemporary",material:"performance_fabric",colors_available:["oyster","cinnamon","dove gray","black"],price_retail:5200,price_wholesale_tier1:2860,price_wholesale_tier2:2600,price_wholesale_tier3:2340,inventory_in_stock:7,inventory_in_production:15,lead_time_weeks:14,dimensions_length:90,dimensions_width:38,dimensions_height:34,dimensions_seat_height:18,weight_lbs:185,description:"A streamlined contemporary sofa with extra-wide arms, deep seating, and a gracefully curved back. Upholstered in premium performance fabric.",features:["Extra-wide arms","Deep seat","Kiln-dried frame","8-way hand-tied springs"],certifications:["BIFMA","CertiPUR-US"],rating:4.7,review_count:43,warranty_years:3,shipping_cost:380,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},
  {manufacturer_name:"Caracole",sku:"CAR-DIN-001",name:"Adela Lacquer Dining Table",category:"dining_table",style:"contemporary",material:"glass",colors_available:["glossy white","glossy black","champagne"],price_retail:4800,price_wholesale_tier1:2640,price_wholesale_tier2:2400,price_wholesale_tier3:2160,inventory_in_stock:5,inventory_in_production:10,lead_time_weeks:16,dimensions_length:84,dimensions_width:42,dimensions_height:30,weight_lbs:200,description:"A high-gloss lacquer dining table with a sculptural four-leg base finished in brushed gold. The pristine top reflects the room, making any dining setting feel glamorous and intentional.",features:["High-gloss lacquer top","Brushed gold base","Seats 6-8","Scratch-resistant surface"],certifications:["Greenguard Gold"],rating:4.8,review_count:21,warranty_years:3,shipping_cost:490,thumbnail:"https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80",images:["https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // UNIVERSAL FURNITURE — Mid-Range
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Universal Furniture",sku:"UNI-SOF-001",name:"Miranda Performance Sectional",category:"sectional",style:"transitional",material:"performance_fabric",colors_available:["dove","pewter","caramel","sage","navy"],price_retail:4400,price_wholesale_tier1:2420,price_wholesale_tier2:2200,price_wholesale_tier3:1980,inventory_in_stock:22,inventory_in_production:35,lead_time_weeks:7,dimensions_length:115,dimensions_width:88,dimensions_height:35,dimensions_seat_height:20,weight_lbs:280,description:"A family-friendly sectional built to handle everyday use with ease. The oversized cushions and wide arms make it the perfect spot for movie night, while the performance fabric handles spills and pets.",features:["Stain-resistant fabric","Reversible chaise","USB charging in arm","Removable covers"],certifications:["CertiPUR-US","BIFMA"],rating:4.6,review_count:178,warranty_years:3,shipping_cost:490,thumbnail:"https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=600&q=80",images:["https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=800&q=80"],status:"active"},
  {manufacturer_name:"Universal Furniture",sku:"UNI-BED-001",name:"Getaway Scandinavian Platform Bed",category:"bed",style:"scandinavian",material:"wood",colors_available:["natural ash","white","charcoal"],price_retail:1800,price_wholesale_tier1:990,price_wholesale_tier2:900,price_wholesale_tier3:810,inventory_in_stock:30,inventory_in_production:40,lead_time_weeks:5,dimensions_length:86,dimensions_width:84,dimensions_height:38,weight_lbs:150,description:"A beautifully simple platform bed in the Scandinavian tradition, with a slatted base and a headboard that balances proportion and understated detail.",features:["Solid ash wood","Slatted base","No box spring","Full through Cal King"],certifications:["FSC Certified","Greenguard"],rating:4.5,review_count:214,warranty_years:3,shipping_cost:320,thumbnail:"https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=600&q=80",images:["https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800&q=80"],status:"active"},
  {manufacturer_name:"Universal Furniture",sku:"UNI-DSK-001",name:"New Economy Home Office Desk",category:"desk",style:"transitional",material:"wood",colors_available:["dark oak","light oak","white"],price_retail:950,price_wholesale_tier1:523,price_wholesale_tier2:475,price_wholesale_tier3:428,inventory_in_stock:50,inventory_in_production:60,lead_time_weeks:4,dimensions_length:54,dimensions_width:24,dimensions_height:30,weight_lbs:75,description:"A clean and functional home office desk with a keyboard tray, two utility drawers, and a broad work surface. The simple design fits both traditional and contemporary home offices.",features:["Keyboard tray","Two drawers","Cable management port","Optional hutch"],certifications:["BIFMA","Greenguard"],rating:4.4,review_count:134,warranty_years:3,shipping_cost:185,thumbnail:"https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80",images:["https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80"],status:"active"},
  {manufacturer_name:"Universal Furniture",sku:"UNI-DIN-001",name:"Weekender Wire-Brush Dining Table",category:"dining_table",style:"transitional",material:"wood",colors_available:["coastal white","driftwood","charcoal"],price_retail:1400,price_wholesale_tier1:770,price_wholesale_tier2:700,price_wholesale_tier3:630,inventory_in_stock:28,inventory_in_production:40,lead_time_weeks:5,dimensions_length:72,dimensions_width:38,dimensions_height:30,weight_lbs:120,description:"A relaxed rectangular dining table with a wire-brushed wood top and architectural X-base. The casual yet polished look fits farmhouse, coastal, and eclectic dining rooms.",features:["Wire-brushed finish","X-base","Seats 6","Leaves available"],certifications:["FSC Certified"],rating:4.5,review_count:91,warranty_years:3,shipping_cost:260,thumbnail:"https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80",images:["https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"],status:"active"},
  {manufacturer_name:"Universal Furniture",sku:"UNI-DRS-001",name:"Streamline Minimalist Dresser",category:"dresser",style:"modern",material:"wood",colors_available:["matte white","matte black","light oak"],price_retail:1250,price_wholesale_tier1:688,price_wholesale_tier2:625,price_wholesale_tier3:563,inventory_in_stock:35,inventory_in_production:45,lead_time_weeks:5,dimensions_length:60,dimensions_width:18,dimensions_height:34,weight_lbs:145,description:"A no-frills, beautifully made dresser with six equal-sized drawers and recessed finger-pull hardware for an ultra-clean facade.",features:["Six full-extension drawers","Soft-close mechanism","Finger-pull hardware","Anti-tip strap"],certifications:["BIFMA","Greenguard"],rating:4.6,review_count:118,warranty_years:3,shipping_cost:240,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},
  {manufacturer_name:"Universal Furniture",sku:"UNI-CHR-001",name:"Coastal Living Swivel Chair",category:"chair",style:"transitional",material:"performance_fabric",colors_available:["sea glass","sand","white","navy"],price_retail:1100,price_wholesale_tier1:605,price_wholesale_tier2:550,price_wholesale_tier3:495,inventory_in_stock:40,inventory_in_production:50,lead_time_weeks:5,dimensions_length:30,dimensions_width:32,dimensions_height:34,dimensions_seat_height:19,weight_lbs:46,description:"A plush swivel chair inspired by the relaxed coastal lifestyle, with a soft upholstered shell and a smooth 360-degree swivel base. Perfect for both living rooms and sunrooms.",features:["360° swivel","Performance fabric","Down-blend cushion","5-star base"],certifications:["CertiPUR-US"],rating:4.5,review_count:86,warranty_years:3,shipping_cost:155,thumbnail:"https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&q=80",images:["https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // CURREY & COMPANY — Designer Luxury
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Currey & Company",sku:"CC-LGT-001",name:"Parish Iron Chandelier",category:"lighting",style:"bohemian",material:"metal",colors_available:["gold leaf","silver leaf","antique bronze"],price_retail:3100,price_wholesale_tier1:1705,price_wholesale_tier2:1550,price_wholesale_tier3:1395,inventory_in_stock:10,inventory_in_production:15,lead_time_weeks:12,dimensions_length:36,dimensions_width:36,dimensions_height:36,weight_lbs:28,description:"A showstopping chandelier featuring a profusion of hand-forged iron arms radiating from a central globe, each holding a delicate flame-tip bulb. Its organic complexity creates a dramatic focal point.",features:["Hand-forged iron","20 candelabra bulbs","Adjustable chain","Dimmable"],certifications:["UL Listed"],rating:4.9,review_count:34,warranty_years:2,shipping_cost:195,thumbnail:"https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=600&q=80",images:["https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&q=80"],status:"active"},
  {manufacturer_name:"Currey & Company",sku:"CC-LGT-002",name:"Spellbound Crystal Floor Lamp",category:"lighting",style:"bohemian",material:"metal",colors_available:["gold leaf","matte black"],price_retail:980,price_wholesale_tier1:539,price_wholesale_tier2:490,price_wholesale_tier3:441,inventory_in_stock:22,inventory_in_production:18,lead_time_weeks:10,dimensions_length:14,dimensions_width:14,dimensions_height:65,weight_lbs:15,description:"A whimsical floor lamp with cascading twig-like iron branches supporting individually placed crystal drops that catch and scatter ambient light.",features:["Hand-applied gold leaf","Crystal accents","Linen shade","150W max"],certifications:["UL Listed"],rating:4.7,review_count:28,warranty_years:2,shipping_cost:125,thumbnail:"https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=600&q=80",images:["https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&q=80"],status:"active"},
  {manufacturer_name:"Currey & Company",sku:"CC-LGT-003",name:"Huxley Woven Rattan Pendant",category:"lighting",style:"bohemian",material:"rattan",colors_available:["natural","bleached"],price_retail:540,price_wholesale_tier1:297,price_wholesale_tier2:270,price_wholesale_tier3:243,inventory_in_stock:30,inventory_in_production:20,lead_time_weeks:10,dimensions_length:22,dimensions_width:22,dimensions_height:18,weight_lbs:5,description:"A hand-woven rattan pendant that creates the warm, dappled light of a tropical escape. The open weave casts dramatic shadow patterns on walls and ceilings.",features:["Hand-woven rattan","Adjustable cord","E26 socket","Indoor use"],certifications:["UL Listed"],rating:4.8,review_count:55,warranty_years:2,shipping_cost:55,thumbnail:"https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=600&q=80",images:["https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=800&q=80"],status:"active"},
  {manufacturer_name:"Currey & Company",sku:"CC-CHR-001",name:"Lucie Rattan Occasional Chair",category:"chair",style:"bohemian",material:"rattan",colors_available:["natural","black"],price_retail:1450,price_wholesale_tier1:798,price_wholesale_tier2:725,price_wholesale_tier3:653,inventory_in_stock:18,inventory_in_production:20,lead_time_weeks:12,dimensions_length:28,dimensions_width:30,dimensions_height:36,dimensions_seat_height:18,weight_lbs:32,description:"A delicate yet sturdy occasional chair with an intricately woven rattan back and hand-painted iron legs. Equally at home in eclectic and transitional interiors.",features:["Handwoven rattan","Iron frame","Cushion sold separately","Indoor use"],certifications:["Rainforest Alliance"],rating:4.6,review_count:41,warranty_years:2,shipping_cost:160,thumbnail:"https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600&q=80",images:["https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // GABBY HOME — Mid/Upper-Mid Coastal
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Gabby Home",sku:"GAB-SOF-001",name:"Clyde Slipcovered Coastal Sofa",category:"sofa",style:"transitional",material:"linen",colors_available:["white linen","natural linen","blue denim","light gray"],price_retail:3100,price_wholesale_tier1:1705,price_wholesale_tier2:1550,price_wholesale_tier3:1395,inventory_in_stock:26,inventory_in_production:30,lead_time_weeks:8,dimensions_length:86,dimensions_width:38,dimensions_height:35,dimensions_seat_height:20,weight_lbs:155,description:"A coastal-casual slipcovered sofa that feels lived-in from day one. The loose slipcover is machine washable, the cushions are filled with down-blend for ultimate comfort.",features:["Machine-washable slipcover","Down-blend cushions","Solid oak legs","Sinuous spring base"],certifications:["CertiPUR-US"],rating:4.7,review_count:95,warranty_years:3,shipping_cost:320,thumbnail:"https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=600&q=80",images:["https://images.unsplash.com/photo-1493663284031-b7e3aefcae8e?w=800&q=80"],status:"active"},
  {manufacturer_name:"Gabby Home",sku:"GAB-CHR-001",name:"Margot Velvet Accent Chair",category:"chair",style:"bohemian",material:"velvet",colors_available:["rust","olive","cream","sky blue"],price_retail:1400,price_wholesale_tier1:770,price_wholesale_tier2:700,price_wholesale_tier3:630,inventory_in_stock:34,inventory_in_production:20,lead_time_weeks:6,dimensions_length:30,dimensions_width:32,dimensions_height:33,dimensions_seat_height:18,weight_lbs:48,description:"A plush accent chair with a casual bucket silhouette and tapered wood legs. The soft velvet upholstery and earthy colorways suit bohemian, coastal, and relaxed-luxury interiors.",features:["Tight back and seat","Turned wood legs","COM available","Ships assembled"],certifications:["CertiPUR-US","Greenguard"],rating:4.6,review_count:72,warranty_years:3,shipping_cost:165,thumbnail:"https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&q=80",images:["https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80"],status:"active"},
  {manufacturer_name:"Gabby Home",sku:"GAB-TAB-001",name:"Hayworth Solid Wood Coffee Table",category:"coffee_table",style:"transitional",material:"wood",colors_available:["bleached wood","dark walnut","painted white"],price_retail:1100,price_wholesale_tier1:605,price_wholesale_tier2:550,price_wholesale_tier3:495,inventory_in_stock:30,inventory_in_production:25,lead_time_weeks:6,dimensions_length:52,dimensions_width:28,dimensions_height:18,weight_lbs:70,description:"A generous rectangular coffee table with a solid wood top and slatted lower shelves offering ample storage. The bleached finish suits coastal and Hamptons-style interiors.",features:["Solid hardwood top","Two lower shelves","3 finishes available","Generous scale"],certifications:["FSC Certified"],rating:4.5,review_count:63,warranty_years:3,shipping_cost:195,thumbnail:"https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600&q=80",images:["https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80"],status:"active"},
  {manufacturer_name:"Gabby Home",sku:"GAB-DIN-001",name:"Palmer Turned-Leg Dining Table",category:"dining_table",style:"transitional",material:"wood",colors_available:["whitewash","natural oak","dark walnut"],price_retail:2000,price_wholesale_tier1:1100,price_wholesale_tier2:1000,price_wholesale_tier3:900,inventory_in_stock:15,inventory_in_production:20,lead_time_weeks:7,dimensions_length:78,dimensions_width:38,dimensions_height:30,weight_lbs:140,description:"A warm and welcoming dining table with a turned-leg base and a solid wood top finished in a wire-brush technique that highlights natural grain.",features:["Solid hardwood","Turned legs","Wire-brushed finish","Seats 6","Extension available"],certifications:["FSC Certified"],rating:4.7,review_count:54,warranty_years:3,shipping_cost:295,thumbnail:"https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80",images:["https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"],status:"active"},
  {manufacturer_name:"Gabby Home",sku:"GAB-BED-001",name:"Sebastian Curved Upholstered Bed",category:"bed",style:"transitional",material:"linen",colors_available:["oatmeal","slate blue","soft gray","ivory"],price_retail:2400,price_wholesale_tier1:1320,price_wholesale_tier2:1200,price_wholesale_tier3:1080,inventory_in_stock:16,inventory_in_production:22,lead_time_weeks:8,dimensions_length:88,dimensions_width:86,dimensions_height:52,weight_lbs:200,description:"A relaxed-luxury bed with a gracefully curved upholstered headboard and a low footboard that feels both substantial and light. Tight smooth linen upholstery keeps the look refined.",features:["Belgian linen","No box spring","Solid hardwood frame","Available Queen and King"],certifications:["Greenguard Gold","CertiPUR-US"],rating:4.7,review_count:68,warranty_years:3,shipping_cost:420,thumbnail:"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",images:["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // HICKORY CHAIR — Heirloom Luxury
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Hickory Chair",sku:"HIC-SOF-001",name:"Metropolitan Tight-Back Sofa",category:"sofa",style:"transitional",material:"linen",colors_available:["cream","dove gray","taupe","dusty blue"],price_retail:6800,price_wholesale_tier1:3740,price_wholesale_tier2:3400,price_wholesale_tier3:3060,inventory_in_stock:5,inventory_in_production:10,lead_time_weeks:16,dimensions_length:90,dimensions_width:38,dimensions_height:33,dimensions_seat_height:18,weight_lbs:165,description:"A classic Hickory Chair tight-back sofa made with the brand's legendary 8-way hand-tied construction on a kiln-dried hardwood frame. Each piece is built in Hickory, NC by skilled craftspeople who have worked there for decades.",features:["8-way hand-tied springs","Kiln-dried hardwood","Down/feather seat cushions","COM available","Made in USA"],certifications:["BIFMA","Greenguard Gold","Made in USA"],rating:4.9,review_count:22,warranty_years:10,shipping_cost:480,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},
  {manufacturer_name:"Hickory Chair",sku:"HIC-CHR-001",name:"Alexa Hampton Arm Chair",category:"chair",style:"traditional",material:"velvet",colors_available:["antique gold","dusty rose","sage green","navy"],price_retail:3600,price_wholesale_tier1:1980,price_wholesale_tier2:1800,price_wholesale_tier3:1620,inventory_in_stock:10,inventory_in_production:12,lead_time_weeks:16,dimensions_length:30,dimensions_width:32,dimensions_height:38,dimensions_seat_height:18,weight_lbs:52,description:"Part of the Alexa Hampton collection for Hickory Chair, this carved wood-framed arm chair blends traditional European forms with American craftsmanship. The scalloped back and turned legs are carved by hand.",features:["Hand-carved wood frame","8-way hand-tied springs","Down/feather cushion","COM available","Made in USA"],certifications:["Greenguard Gold","Made in USA"],rating:4.9,review_count:18,warranty_years:10,shipping_cost:280,thumbnail:"https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80",images:["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80"],status:"active"},
  {manufacturer_name:"Hickory Chair",sku:"HIC-DIN-001",name:"Thomas O'Brien Parsons Dining Table",category:"dining_table",style:"transitional",material:"wood",colors_available:["bleached walnut","ebony","warm walnut"],price_retail:5400,price_wholesale_tier1:2970,price_wholesale_tier2:2700,price_wholesale_tier3:2430,inventory_in_stock:4,inventory_in_production:8,lead_time_weeks:18,dimensions_length:84,dimensions_width:42,dimensions_height:30,weight_lbs:210,description:"A parsons-style dining table from the Thomas O'Brien collection, featuring a solid walnut top with a hand-rubbed oil finish and tapered solid-wood legs. Built to heirloom standards in the USA.",features:["Solid American walnut","Hand-rubbed oil finish","Extension leaf available","Made in USA"],certifications:["FSC Certified","Made in USA"],rating:4.9,review_count:14,warranty_years:10,shipping_cost:550,thumbnail:"https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80",images:["https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"],status:"active"},
  {manufacturer_name:"Hickory Chair",sku:"HIC-BED-001",name:"Ian Shearer Upholstered Bed",category:"bed",style:"contemporary",material:"linen",colors_available:["warm white","pale gray","natural linen"],price_retail:7200,price_wholesale_tier1:3960,price_wholesale_tier2:3600,price_wholesale_tier3:3240,inventory_in_stock:3,inventory_in_production:8,lead_time_weeks:18,dimensions_length:88,dimensions_width:86,dimensions_height:54,weight_lbs:225,description:"A fully upholstered platform bed from Hickory Chair's Ian Shearer collection, featuring a gently curved headboard and solid wood base frame. The precision tailoring and high-density foam construction are made to outlast decades of use.",features:["Solid hardwood frame","High-density foam","Tailored upholstery","COM available","Made in USA"],certifications:["Greenguard Gold","CertiPUR-US","Made in USA"],rating:5.0,review_count:9,warranty_years:10,shipping_cost:680,thumbnail:"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",images:["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // THEODORE ALEXANDER — Ultra-Luxury Heritage
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Theodore Alexander",sku:"TA-DIN-001",name:"Althorp Living History Extending Dining Table",category:"dining_table",style:"traditional",material:"wood",colors_available:["cherry","mahogany","walnut burl"],price_retail:9800,price_wholesale_tier1:5390,price_wholesale_tier2:4900,price_wholesale_tier3:4410,inventory_in_stock:2,inventory_in_production:5,lead_time_weeks:20,dimensions_length:96,dimensions_width:48,dimensions_height:30,weight_lbs:320,description:"An extending dining table from the Althorp Living History collection, inspired by the original furniture at Althorp Estate, ancestral home of Princess Diana. Hand-carved and finished by master craftspeople over 400 hours.",features:["Solid mahogany","Hand-carved detail","Three 20\" leaves","Seats up to 16","COM available"],certifications:["FSC Certified","Made in Indonesia by Master Craftspeople"],rating:4.9,review_count:8,warranty_years:5,shipping_cost:1200,thumbnail:"https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80",images:["https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"],status:"active"},
  {manufacturer_name:"Theodore Alexander",sku:"TA-DRS-001",name:"Zeugma Bone Inlay Chest",category:"dresser",style:"traditional",material:"wood",colors_available:["ebonized","natural bone","tortoiseshell"],price_retail:7600,price_wholesale_tier1:4180,price_wholesale_tier2:3800,price_wholesale_tier3:3420,inventory_in_stock:3,inventory_in_production:6,lead_time_weeks:20,dimensions_length:48,dimensions_width:18,dimensions_height:50,weight_lbs:145,description:"A six-drawer chest embellished with thousands of individually placed bone inlay tiles in a geometric mosaic pattern. No two pieces are identical — each is a unique work of artisanal craft.",features:["Hand-set bone inlay","Polished chrome pulls","Six smooth-glide drawers","Certificate of authenticity"],certifications:["CITES Compliant"],rating:4.9,review_count:6,warranty_years:5,shipping_cost:850,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},
  {manufacturer_name:"Theodore Alexander",sku:"TA-CHR-001",name:"Berkeley Leather Library Chair",category:"chair",style:"traditional",material:"leather",colors_available:["cognac","British tan","antiqued black"],price_retail:4200,price_wholesale_tier1:2310,price_wholesale_tier2:2100,price_wholesale_tier3:1890,inventory_in_stock:6,inventory_in_production:8,lead_time_weeks:18,dimensions_length:32,dimensions_width:34,dimensions_height:40,dimensions_seat_height:18,weight_lbs:78,description:"A button-tufted leather library chair with a carved walnut frame and antique brass nailhead trim, modeled after classic English club chairs. The generous seat and tall back encourage long hours of reading.",features:["Button-tufted leather","Hand-carved frame","Antique brass nailheads","Hand-tied springs"],certifications:["Leather Working Group Gold"],rating:4.9,review_count:12,warranty_years:5,shipping_cost:340,thumbnail:"https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80",images:["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // MAITLAND-SMITH — Ultra-Luxury Artisan
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Maitland-Smith",sku:"MS-COF-001",name:"Stratford Hand-Painted Coffee Table",category:"coffee_table",style:"traditional",material:"wood",colors_available:["antique gold","ebonized","tortoiseshell"],price_retail:6400,price_wholesale_tier1:3520,price_wholesale_tier2:3200,price_wholesale_tier3:2880,inventory_in_stock:2,inventory_in_production:4,lead_time_weeks:24,dimensions_length:54,dimensions_width:30,dimensions_height:18,weight_lbs:120,description:"A hand-painted cocktail table with gilded trompe l'oeil detailing and a glass top that protects the artisanal surface beneath. Each piece requires up to 80 hours of hand-finishing by Maitland-Smith's master craftspeople.",features:["Hand-painted finish","Tempered glass top","Gilt accents","80+ hours of hand-finishing"],certifications:["Certificate of Artisanship"],rating:4.9,review_count:5,warranty_years:3,shipping_cost:750,thumbnail:"https://images.unsplash.com/photo-1592078615290-033ee584e267?w=600&q=80",images:["https://images.unsplash.com/photo-1592078615290-033ee584e267?w=800&q=80"],status:"active"},
  {manufacturer_name:"Maitland-Smith",sku:"MS-DRS-001",name:"Regency Marquetry Dresser",category:"dresser",style:"traditional",material:"wood",colors_available:["satinwood","rosewood","ebony inlay"],price_retail:12500,price_wholesale_tier1:6875,price_wholesale_tier2:6250,price_wholesale_tier3:5625,inventory_in_stock:1,inventory_in_production:3,lead_time_weeks:28,dimensions_length:60,dimensions_width:20,dimensions_height:38,weight_lbs:220,description:"A six-drawer dresser with an intricate marquetry pattern on the drawer fronts and top, composed of hundreds of individually cut and placed wood veneers in contrasting tones. A defining statement piece for the most distinguished bedrooms.",features:["Hand-cut wood marquetry","Ormolu-style hardware","Dovetail drawer joints","Fully finished interior","Made in Philippines by master craftspeople"],certifications:["CITES Compliant","Certificate of Artisanship"],rating:5.0,review_count:4,warranty_years:5,shipping_cost:1400,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // LEXINGTON HOME BRANDS — Luxury Lifestyle Collections
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Lexington Home Brands",sku:"LEX-SOF-001",name:"Ariana Leather Sofa",category:"sofa",style:"transitional",material:"leather",colors_available:["cream","charcoal","tan","chocolate"],price_retail:4900,price_wholesale_tier1:2695,price_wholesale_tier2:2450,price_wholesale_tier3:2205,inventory_in_stock:10,inventory_in_production:16,lead_time_weeks:12,dimensions_length:92,dimensions_width:39,dimensions_height:35,dimensions_seat_height:19,weight_lbs:180,description:"A luxuriously scaled sofa with wide track arms and a deep seat, upholstered in top-grain leather with contrast stitching. The simple, elegant profile suits both traditional and contemporary living rooms.",features:["Top-grain leather","Contrast stitching","8-way hand-tied springs","Down/fiber seat cushions"],certifications:["Leather Working Group Silver"],rating:4.7,review_count:61,warranty_years:5,shipping_cost:380,thumbnail:"https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=600&q=80",images:["https://images.unsplash.com/photo-1484101403633-562f891dc89a?w=800&q=80"],status:"active"},
  {manufacturer_name:"Lexington Home Brands",sku:"LEX-BED-001",name:"Ocean Breeze Upholstered Queen Bed",category:"bed",style:"contemporary",material:"performance_fabric",colors_available:["sea foam","sandy beige","navy","white"],price_retail:3200,price_wholesale_tier1:1760,price_wholesale_tier2:1600,price_wholesale_tier3:1440,inventory_in_stock:14,inventory_in_production:18,lead_time_weeks:10,dimensions_length:86,dimensions_width:66,dimensions_height:58,weight_lbs:190,description:"A coastal-inspired upholstered bed with a gracefully arched headboard and a solid walnut base. The performance fabric is treated for moisture resistance, making it ideal for beach homes and humid climates.",features:["Arched headboard","Performance fabric","Solid walnut base","No box spring required"],certifications:["Greenguard Gold","CertiPUR-US"],rating:4.7,review_count:48,warranty_years:5,shipping_cost:420,thumbnail:"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",images:["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80"],status:"active"},
  {manufacturer_name:"Lexington Home Brands",sku:"LEX-OUT-001",name:"Laguna Beach Outdoor Sofa",category:"outdoor",style:"contemporary",material:"performance_fabric",colors_available:["white","charcoal","sand"],price_retail:3600,price_wholesale_tier1:1980,price_wholesale_tier2:1800,price_wholesale_tier3:1620,inventory_in_stock:12,inventory_in_production:20,lead_time_weeks:10,dimensions_length:90,dimensions_width:36,dimensions_height:30,dimensions_seat_height:17,weight_lbs:160,description:"A weather-resistant outdoor sofa with a powder-coated aluminum frame and Sunbrella cushions rated for 1,000+ hours of UV exposure. The slim profile and clean lines fit pool decks, rooftop terraces, and covered patios.",features:["Powder-coated aluminum","Sunbrella cushions","1000+ UV hours rated","All-weather hardware"],certifications:["Oeko-Tex","Rainforest Alliance"],rating:4.8,review_count:35,warranty_years:5,shipping_cost:320,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},
  {manufacturer_name:"Lexington Home Brands",sku:"LEX-DIN-001",name:"Rochelle Round Dining Table",category:"dining_table",style:"transitional",material:"wood",colors_available:["white oak","warm walnut","driftwood"],price_retail:2600,price_wholesale_tier1:1430,price_wholesale_tier2:1300,price_wholesale_tier3:1170,inventory_in_stock:14,inventory_in_production:18,lead_time_weeks:9,dimensions_length:54,dimensions_width:54,dimensions_height:30,weight_lbs:130,description:"A round dining table with a solid white oak top and a sculptural tapered pedestal base finished in a contrasting dark tone. The round form encourages intimate conversation around every setting.",features:["Solid white oak top","Sculptural pedestal base","Seats 4-6","Lazy Susan insert available"],certifications:["FSC Certified"],rating:4.7,review_count:42,warranty_years:5,shipping_cost:310,thumbnail:"https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80",images:["https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // ART FURNITURE — Mid/Upper-Mid
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"ART Furniture",sku:"ARTF-SOF-001",name:"Palisade Track Arm Sofa",category:"sofa",style:"contemporary",material:"performance_fabric",colors_available:["slate","cream","charcoal","taupe"],price_retail:2800,price_wholesale_tier1:1540,price_wholesale_tier2:1400,price_wholesale_tier3:1260,inventory_in_stock:20,inventory_in_production:30,lead_time_weeks:8,dimensions_length:88,dimensions_width:38,dimensions_height:32,dimensions_seat_height:18,weight_lbs:148,description:"A handsomely proportioned track-arm sofa with tight seating and a low back profile that maximizes sight lines in open plan living rooms. Upholstered in a tightly woven performance fabric with a subtle texture.",features:["Track arms","Low back profile","Performance fabric","Kiln-dried hardwood frame"],certifications:["CertiPUR-US","BIFMA"],rating:4.6,review_count:73,warranty_years:3,shipping_cost:295,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},
  {manufacturer_name:"ART Furniture",sku:"ARTF-DIN-001",name:"Epicenters Austin Dining Table",category:"dining_table",style:"industrial",material:"wood",colors_available:["reclaimed pine","dark iron","natural"],price_retail:2200,price_wholesale_tier1:1210,price_wholesale_tier2:1100,price_wholesale_tier3:990,inventory_in_stock:18,inventory_in_production:25,lead_time_weeks:8,dimensions_length:80,dimensions_width:40,dimensions_height:30,weight_lbs:165,description:"A live-edge inspired dining table from the Epicenters Austin collection, featuring a solid pine top with a natural wax finish on a powder-coated iron base. The warm-meets-industrial look suits loft and farmhouse dining rooms.",features:["Solid pine top","Natural wax finish","Iron base","Seats 6-8"],certifications:["FSC Certified","BIFMA"],rating:4.6,review_count:55,warranty_years:3,shipping_cost:290,thumbnail:"https://images.unsplash.com/photo-1617806118233-18e1de247200?w=600&q=80",images:["https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800&q=80"],status:"active"},
  {manufacturer_name:"ART Furniture",sku:"ARTF-BED-001",name:"Geode Platform Bed",category:"bed",style:"contemporary",material:"wood",colors_available:["natural quartz","gray agate","dark onyx"],price_retail:2400,price_wholesale_tier1:1320,price_wholesale_tier2:1200,price_wholesale_tier3:1080,inventory_in_stock:16,inventory_in_production:22,lead_time_weeks:8,dimensions_length:86,dimensions_width:86,dimensions_height:44,weight_lbs:190,description:"A platform bed with a bold bookmatched wood veneer headboard in patterns that echo natural geode cross-sections. The floating base appears to hover over the floor, adding a sculptural quality.",features:["Bookmatched veneer headboard","Floating base design","Solid wood frame","Available Queen and King"],certifications:["BIFMA","Greenguard"],rating:4.7,review_count:38,warranty_years:3,shipping_cost:380,thumbnail:"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",images:["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80"],status:"active"},
  {manufacturer_name:"ART Furniture",sku:"ARTF-BSH-001",name:"Frame Bookcase with Doors",category:"bookshelf",style:"contemporary",material:"wood",colors_available:["matte white","dark espresso","natural walnut"],price_retail:1800,price_wholesale_tier1:990,price_wholesale_tier2:900,price_wholesale_tier3:810,inventory_in_stock:22,inventory_in_production:28,lead_time_weeks:7,dimensions_length:42,dimensions_width:16,dimensions_height:80,weight_lbs:130,description:"A tall bookcase with open upper shelves and solid lower doors that conceal storage. The solid wood frame and clean proportions suit contemporary, transitional, and Scandinavian interiors.",features:["Open upper shelves","Solid lower doors","4 adjustable shelves","Anti-tip hardware"],certifications:["BIFMA","Greenguard"],rating:4.6,review_count:47,warranty_years:3,shipping_cost:220,thumbnail:"https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&q=80",images:["https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800&q=80"],status:"active"},

  // ══════════════════════════════════════════════════════
  // VANGUARD FURNITURE — High-End Custom
  // ══════════════════════════════════════════════════════
  {manufacturer_name:"Vanguard Furniture",sku:"VAN-SOF-001",name:"Michael Weiss Tightback Sofa",category:"sofa",style:"contemporary",material:"performance_fabric",colors_available:["oyster","dove","navy","charcoal","biscuit"],price_retail:5900,price_wholesale_tier1:3245,price_wholesale_tier2:2950,price_wholesale_tier3:2655,inventory_in_stock:6,inventory_in_production:12,lead_time_weeks:16,dimensions_length:88,dimensions_width:38,dimensions_height:32,dimensions_seat_height:18,weight_lbs:160,description:"A fully custom sofa from Vanguard's Michael Weiss collection, built to order in Conover, NC. The clean track arms and tight back distinguish it as a precision-engineered piece for sophisticated modern interiors.",features:["Built to order","8-way hand-tied springs","COM available","Made in USA","Kiln-dried hardwood"],certifications:["BIFMA","Greenguard Gold","Made in USA"],rating:4.9,review_count:16,warranty_years:5,shipping_cost:480,thumbnail:"https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80",images:["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80"],status:"active"},
  {manufacturer_name:"Vanguard Furniture",sku:"VAN-CHR-001",name:"Wynne Slipper Chair",category:"chair",style:"transitional",material:"velvet",colors_available:["dusty blue","blush","cognac","ivory","sage"],price_retail:2800,price_wholesale_tier1:1540,price_wholesale_tier2:1400,price_wholesale_tier3:1260,inventory_in_stock:12,inventory_in_production:18,lead_time_weeks:14,dimensions_length:28,dimensions_width:30,dimensions_height:34,dimensions_seat_height:16,weight_lbs:44,description:"A legless slipper chair profile with a gentle slope from backrest to seat that encourages deep, relaxed lounging. The low-to-the-ground silhouette makes it ideal for layering in seating arrangements.",features:["Low slipper profile","8-way hand-tied springs","COM available","Made in USA"],certifications:["CertiPUR-US","Made in USA"],rating:4.8,review_count:24,warranty_years:5,shipping_cost:225,thumbnail:"https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&q=80",images:["https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80"],status:"active"},
  {manufacturer_name:"Vanguard Furniture",sku:"VAN-BED-001",name:"Tranquility Shelter Bed",category:"bed",style:"contemporary",material:"linen",colors_available:["natural linen","warm white","pale ash"],price_retail:6200,price_wholesale_tier1:3410,price_wholesale_tier2:3100,price_wholesale_tier3:2790,inventory_in_stock:4,inventory_in_production:8,lead_time_weeks:18,dimensions_length:88,dimensions_width:86,dimensions_height:58,weight_lbs:210,description:"A shelter-style platform bed with floor-to-ceiling upholstered panels that wrap around the head and sides like a cozy cocoon. The minimal form and refined tailoring define modern bedroom luxury.",features:["Shelter-style headboard","Full upholstery","Solid hardwood","Made in USA","COM available"],certifications:["Greenguard Gold","CertiPUR-US","Made in USA"],rating:4.9,review_count:11,warranty_years:5,shipping_cost:620,thumbnail:"https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80",images:["https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80"],status:"active"},
];

// ============================================================
Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (user?.role !== 'admin') {
      return Response.json({ error: 'Admin only' }, { status: 403 });
    }

    const base44sr = base44.asServiceRole;

    // Clear existing products
    let page = 0;
    let deleted = 0;
    while (true) {
      const existing = await base44sr.entities.Product.list('-created_date', 50, page * 50);
      if (!existing || existing.length === 0) break;
      for (const p of existing) {
        await base44sr.entities.Product.delete(p.id);
        deleted++;
      }
      if (existing.length < 50) break;
      page++;
    }

    // Insert all catalog products
    const results = [];
    for (const product of CATALOG) {
      const created = await base44sr.entities.Product.create({
        ...product,
        search_impressions_week: Math.floor(Math.random() * 400) + 50,
        clicks_week: Math.floor(Math.random() * 100) + 10,
        orders_week: Math.floor(Math.random() * 25) + 1,
        inventory_in_production: product.inventory_in_production || Math.floor(Math.random() * 50) + 5,
        inventory_in_transit: Math.floor(Math.random() * 20),
      });
      results.push(created);
    }

    return Response.json({ success: true, count: results.length, deleted });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});